import json

with open('messages/zh.json', 'r') as f:
    zh = json.load(f)

with open('messages/ko.json', 'r') as f:
    ko = json.load(f)

def set_nested(d, path, value):
    keys = path.split('.')
    for key in keys[:-1]:
        if key.isdigit():
            d = d[int(key)]
        else:
            d = d[key]
    last = keys[-1]
    if last.isdigit():
        d[int(last)] = value
    else:
        d[last] = value

# Find all Chinese strings in zh.json and map to Korean
def find_chinese(obj, path=""):
    results = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            results.extend(find_chinese(v, f"{path}.{k}"))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            results.extend(find_chinese(v, f"{path}[{i}]"))
    elif isinstance(obj, str) and obj:
        has_cjk = any('\u4e00' <= c <= '\u9fff' for c in obj)
        if has_cjk:
            results.append((path, obj))
    return results

chinese_strings = find_chinese(zh)
print(f"Found {len(chinese_strings)} Chinese strings to translate to Korean")

# Korean translations for all Chinese strings
korean = {
    # Nav
    "nav.triggers.products": "제품",
    "nav.triggers.marketplace": "마켓플레이스",
    "nav.triggers.solutions": "솔루션",
    "nav.triggers.resources": "리소스",
    "nav.links.pricing": "가격",
    "nav.links.login": "로그인",
    "nav.links.signup": "무료 가입",
    "nav.categories.intelligence": "인텔리전스",
    "nav.categories.platform": "플랫폼",
    "nav.categories.buyDomains": "도메인 구매",
    "nav.categories.sellDomains": "도메인 판매",
    "nav.categories.byRole": "역할별",
    "nav.categories.byNeed": "필요별",
    "nav.categories.explore": "탐색",
    "nav.categories.support": "지원",
    "nav.items.domainLookup.title": "도메인 조회",
    "nav.items.domainLookup.desc": "무료 도구: WHOIS 데이터, DNS 레코드.",
    "nav.items.appraisal.title": "16차원 평가",
    "nav.items.appraisal.desc": "16개 차원 기반의 심층 도메인 가치 평가 및 시장 기반 가격 책정.",
    "nav.items.domainScanner.title": "도메인 스캐너",
    "nav.items.domainScanner.desc": "프리미엄 도구: DA 점수, 스팸 메일 감지, 백링크 분석 및 색인 상태. 구독 필요.",
    "nav.items.extendedInsights.title": "확장 인사이트",
    "nav.items.extendedInsights.desc": "프리미엄 도구: 심층 DNS 레코드, USPTO/WIPO 상표 조회 및 WHOIS 기록.",
    "nav.items.bulkAudit.title": "대량 도메인 감사",
    "nav.items.bulkAudit.desc": "프리미엄 도구: 한 번에 최대 1000개 도메인을 일괄 처리하고 분석합니다.",
    "nav.items.apiAccess.title": "API 인터페이스",
    "nav.items.apiAccess.desc": "대규모 프로그래밍 방식 도메인 인텔리전스 분석을 위한 RESTful API.",
    "nav.items.trademarkMonitor.title": "상표 모니터",
    "nav.items.trademarkMonitor.desc": "USPTO/WIPO 충돌 감지 및 자동 알림.",
    "nav.items.domainDatabase.title": "도메인 데이터베이스",
    "nav.items.domainDatabase.desc": "포괄적인 TLD 등록 정보 및 만료 추적.",
    "nav.items.standardMarketplace.title": "표준 마켓플레이스",
    "nav.items.standardMarketplace.desc": "전체 데이터가 표시되는 프리미엄 도메인을 탐색합니다. 이름 숨김 — 공개 비용 지불.",
    "nav.items.curatedDomains.title": "큐레이션 도메인",
    "nav.items.curatedDomains.desc": "우리 팀이 검증한 엄선된 프리미엄 도메인.",
    "nav.items.tryYourLuck.title": "행운 시도",
    "nav.items.tryYourLuck.desc": "TLD를 선택하고, 3개 상자를 돌려, 프리미엄 도메인을 공개합니다. 귀하에게만 독점 잠깁니다.",
    "nav.items.listDomain.title": "도메인 판매",
    "nav.items.listDomain.desc": "Ceche에서 프리미엄 도메인을 판매하세요. 등록비 $5-$10, 수수료 8-15%.",
    "nav.items.domainInvestors.title": "도메인 투자자",
    "nav.items.domainInvestors.desc": "포트폴리오 수익 분석, 플리퍼 밸류에이션 메트릭 및 도메인 캡처 알림.",
    "nav.items.startupFounders.title": "스타트업 창업자",
    "nav.items.startupFounders.desc": "브랜드 인덱스, 키워드 발음 가능성 및 확장 침투 분석.",
    "nav.items.seoAgencies.title": "SEO 대행사",
    "nav.items.seoAgencies.desc": "만료된 도메인 백링크 권위 점수 및 스팸 페널티 복구 감사.",
    "nav.items.findAvailable.title": "사용 가능한 도메인 찾기",
    "nav.items.findAvailable.desc": "수백만 가지 조합을 스캔하여 사용 가능한 프리미엄 도메인을 찾습니다.",
    "nav.items.researchIntelligence.title": "연구 인텔리전스",
    "nav.items.researchIntelligence.desc": "인수 전 심층 도메인 분석. 현명한 결정을 내리세요.",
    "nav.items.buyPremium.title": "프리미엄 도메인 구매",
    "nav.items.buyPremium.desc": "안전하고 투명한 거래를 통해 고가치 도메인을 확보하세요. 빠르고 안정적입니다.",
    "nav.items.blog.title": "블로그",
    "nav.items.blog.desc": "도메인 투자 팁, 플랫폼 업데이트 및 업계 인사이트.",
    "nav.items.ebooks.title": "전자책",
    "nav.items.ebooks.desc": "도메인 밸류에이션, SEO 및 브랜드 전략에 대한 심층 가이드.",
    "nav.items.caseStudies.title": "사례 연구",
    "nav.items.caseStudies.desc": "도메인 투자자 및 스타트업 창업자의 실제 사례.",
    "nav.items.helpCenter.title": "도움말 센터",
    "nav.items.helpCenter.desc": "모든 Ceche 도구에 대한 문서, FAQ 및 시작 가이드.",
    "nav.items.apiDocs.title": "API 문서",
    "nav.items.apiDocs.desc": "API 참조, 인증 및 통합 가이드.",
    "nav.items.contact.title": "문의하기",
    "nav.items.contact.desc": "도움말, 피드백 또는 파트너십 문의를 위해 지원팀에 연락하세요.",
    "nav.items.changelog.title": "변경 로그",
    "nav.items.changelog.desc": "제품 업데이트, 새로운 기능 및 플랫폼 개선.",
    # Nav sidebar
    "nav.sidebar.overview": "개요",
    "nav.sidebar.documentation": "문서",
    "nav.sidebar.apiReference": "API 참조",
    "nav.sidebar.faq": "자주 묻는 질문",
    "nav.sidebar.contact": "문의하기",
    "nav.sidebar.changelog": "변경 로그",
    # Nav mega menu
    "nav.megaMenu.products": "도메인 인텔리전스를 위한 도구와 API",
    "nav.megaMenu.marketplace": "프리미엄 도메인 매매",
    "nav.megaMenu.solutions": "귀하의 역할과 워크플로에 맞춘 솔루션",
    "nav.megaMenu.resources": "학습 및 지원 받기",
    # Footer
    "footer.tagline": "기업급 도메인 인텔리전스 및 마켓플레이스 플랫폼.",
    "footer.sections.products": "제품",
    "footer.sections.marketplace": "마켓플레이스",
    "footer.sections.company": "회사",
    "footer.sections.legal": "법률",
    "footer.links.domainAppraiser": "도메인 평가기",
    "footer.links.seoScanner": "SEO 스캐너",
    "footer.links.extendedInsights": "확장 인사이트",
    "footer.links.bulkAnalyzer": "대량 분석기",
    "footer.links.apiAccess": "API 인터페이스",
    "footer.links.curatedDomains": "큐레이션 도메인",
    "footer.links.tryYourLuck": "행운 시도",
    "footer.links.sellDomains": "도메인 판매",
    "footer.links.howUnmaskingWorks": "공개 메커니즘",
    "footer.links.about": "회사 소개",
    "footer.links.affiliates": "파트너",
    "footer.links.blog": "블로그",
    "footer.links.contact": "문의하기",
    "footer.links.terms": "이용 약관",
    "footer.links.privacy": "개인정보 처리방침",
    "footer.links.cookies": "쿠키 정책",
    "footer.copyright": "모든 권리 보유.",
    "footer.platform": "도메인 인텔리전스 플랫폼",
    # Home
    "home.hero.title1": "프리미엄 도메인,",
    "home.hero.titleHighlight": "인텔리전스로",
    "home.hero.searchPlaceholder": "임의의 도메인을 검색하세요, 예: brand.com",
    "home.hero.searchButton": "도메인 검색",
    "home.hero.badges.blindListings": "블라인드 목록",
    "home.hero.badges.dimensionIntelligence": "16차원 인텔리전스",
    "home.hero.badges.secureTransactions": "안전한 거래",
    "home.searchTool.badge": "무료 도구",
    "home.searchTool.title": "임의의 도메인 검색",
    "home.searchTool.taken.title": "도메인 등록됨?",
    "home.searchTool.available.title": "도메인 사용 가능?",
    "home.searchTool.appraise.title": "심층 평가",
    "home.builtFor.badge": "대상 사용자",
    "home.builtFor.title": "세 가지 사용자, 하나의 플랫폼",
    "home.builtFor.investors.title": "도메인 투자자",
    "home.builtFor.investors.statLabel": "스캔당 검사 수",
    "home.builtFor.founders.title": "스타트업 창업자",
    "home.builtFor.founders.statLabel": "검사된 차원",
    "home.builtFor.agencies.title": "SEO 대행사",
    "home.builtFor.agencies.statLabel": "도메인당 메트릭",
    "home.marketplace.badge": "마켓플레이스",
    "home.marketplace.title": "프리미엄 이름, 이름 숨김",
    "home.marketplace.cta": "마켓플레이스 둘러보기",
    "home.marketplace.revealPricingTitle": "공개 가격",
    "home.marketplace.tryYourLuckTitle": "행운 시도",
    "home.marketplace.tryYourLuckCta": "행운 시도",
    "home.howItWorks.badge": "작동 방식",
    "home.howItWorks.title": "돌리고, 고르고, 소유하세요",
    "home.howItWorks.step1.title": "TLD 선택",
    "home.howItWorks.step2.title": "돌리고 상자 선택",
    "home.howItWorks.step3.title": "공개 및 등록",
    "home.howItWorks.cta": "지금 행운 시도",
    "home.underTheHood.badge": "기술 아키텍처",
    "home.underTheHood.title": "속도와 신뢰를 위해 구축",
    "home.underTheHood.goroutine.title": "50 워커 고루틴 풀",
    "home.underTheHood.encryption.title": "AES-256-GCM 암호화",
    "home.underTheHood.caching.title": "인메모리 캐싱",
    "home.faq.badge": "자주 묻는 질문",
    "home.faq.title": "자주 묻는 질문",
    "home.worldMap.title": "전 세계 도메인 유동성 가속화",
    "home.worldMap.cta": "평가 시작",
    "home.cta.title": "다음 도메인을 찾을 준비가 되셨나요?",
    "home.cta.signup": "무료 가입",
    "home.cta.pricing": "가격 보기",
    "home.app.welcomeBack": "다시 오셨군요, {name}",
    "home.app.plan": "플랜",
    "home.app.quickActions": "빠른 작업",
    "home.app.appraiseDomain": "도메인 평가 →",
    "home.app.startScan": "스캔 시작 →",
    "home.app.browseMarketplace": "마켓플레이스 둘러보기 →",
    "home.app.apiKeys": "API 키",
    "home.app.manageKeys": "키 관리 →",
    # Pricing
    "pricingPage.hero.badge": "가격",
    "pricingPage.hero.title": "간단하고 투명한 가격",
    "pricingPage.hero.subtitle": "무료로 시작하세요. 더 많은 기능이 필요하면 업그레이드하세요. 언제든 취소 가능.",
    "pricingPage.annual.banner": "연간 결제 시 최대 $260 절약",
    "pricingPage.annual.mostPopular": "가장 인기",
    "pricingPage.plans.free.name": "무료",
    "pricingPage.plans.free.cta": "시작하기",
    "pricingPage.plans.startup.name": "Premium 스타트업",
    "pricingPage.plans.startup.annualNote": "연간 $160 절약",
    "pricingPage.plans.startup.cta": "Premium 시작",
    "pricingPage.plans.enterprise.name": "Premium 엔터프라이즈",
    "pricingPage.plans.enterprise.annualNote": "연간 $260 절약",
    "pricingPage.plans.enterprise.cta": "엔터프라이즈 시작",
    "pricingPage.tryYourLuck.badge": "행운 시도",
    "pricingPage.tryYourLuck.title": "돌리고. 공개하고. 소유하세요.",
    "pricingPage.tryYourLuck.mostPopular": "가장 인기",
    "pricingPage.fees.reveal.badge": "마켓플레이스",
    "pricingPage.fees.reveal.title": "공개 수수료",
    "pricingPage.fees.reveal.headers.tier": "등급",
    "pricingPage.fees.reveal.headers.valueRange": "가치 범위",
    "pricingPage.fees.reveal.headers.fee": "수수료",
    "pricingPage.fees.listing.badge": "판매자",
    "pricingPage.fees.listing.title": "등록 수수료",
    "pricingPage.fees.listing.standard.name": "표준 등록",
    "pricingPage.fees.listing.standard.desc": "30일 노출",
    "pricingPage.fees.listing.priority.name": "우선 배치",
    "pricingPage.fees.listing.priority.desc": "72시간 가속 + 추천",
    "pricingPage.fees.commission.badge": "수수료",
    "pricingPage.fees.commission.title": "판매자 수수료 요율",
    "pricingPage.fees.commission.headers.saleAmount": "판매 금액",
    "pricingPage.fees.commission.headers.rate": "요율",
    "pricingPage.fees.commission.headers.minFee": "최소 수수료",
    "pricingPage.compare.badge": "비교",
    "pricingPage.compare.title": "Ceche vs 경쟁사",
    "pricingPage.compare.headers.feature": "기능",
    "pricingPage.compare.headers.ceche": "Ceche",
    "pricingPage.compare.headers.godaddy": "GoDaddy",
    "pricingPage.compare.headers.sedo": "Sedo",
    "pricingPage.compare.rows.0": "AI 도메인 밸류에이션",
    "pricingPage.compare.rows.1": "16차원 스코어링",
    "pricingPage.compare.rows.2": "WHOIS + DNS 인텔",
    "pricingPage.compare.rows.3": "SEO/DA/스팸 스캔",
    "pricingPage.compare.rows.4": "대량 도메인 감사",
    "pricingPage.compare.rows.5": "상표 모니터링",
    "pricingPage.compare.rows.6": "마켓플레이스 공개 모델",
    "pricingPage.compare.rows.7": "API 접근",
    "pricingPage.compare.rows.8": "무료 티어",
    "pricingPage.cta.title": "준비되셨나요?",
    "pricingPage.cta.signup": "무료 계정 만들기",
    "pricingPage.cta.help": "도움말 센터 방문",
    "pricingPage.cta.lookup": "무료 도메인 조회",
    # Auth
    "auth.login.title": "로그인",
    "auth.login.email": "이메일",
    "auth.login.password": "비밀번호",
    "auth.login.button": "로그인",
    "auth.login.loading": "로그인 중...",
    "auth.login.noAccount": "계정이 없으신가요?",
    "auth.login.signup": "가입",
    "auth.signup.title": "가입",
    "auth.signup.name": "이름",
    "auth.signup.email": "이메일",
    "auth.signup.password": "비밀번호",
    "auth.signup.button": "가입",
    "auth.signup.loading": "계정 생성 중...",
    "auth.signup.hasAccount": "이미 계정이 있으신가요?",
    "auth.signup.login": "로그인",
    # Dashboard
    "dashboard.welcome": "다시 오셨군요, {name}",
    "dashboard.plan": "플랜",
    "dashboard.apiKeys": "API 키",
    "dashboard.manageKeys": "키 관리 →",
    "dashboard.quickActions": "빠른 작업",
    "dashboard.appraise": "도메인 평가 →",
    "dashboard.scan": "스캔 시작 →",
    # Limit
    "limit.title": "속도 제한 도달",
    "limit.signup": "무료 가입",
    "limit.home": "홈으로 돌아가기",
    # Search
    "search.placeholder": "임의의 도메인을 입력하세요, 예: brand.com",
    "search.button": "검색",
    "search.loading": "{domain} 확인 중...",
    "search.available": "등록 가능",
    "search.taken": "등록됨",
    "search.rating": "등급",
    "search.appraise": "이 이름 평가",
    "search.fullAppraisal": "전체 평가",
    "search.copyDomain": "도메인 복사",
    "search.empty": "위에 도메인을 입력하여 사용 가능 여부를 확인하세요",
    # API Keys
    "apikeys.title": "API 키",
    "apikeys.loading": "로딩 중...",
    "apikeys.createTitle": "새 키 생성",
    "apikeys.placeholder": "키 이름 (예: production)",
    "apikeys.create": "생성",
    "apikeys.creating": "생성 중...",
    "apikeys.yourKeys": "내 키",
    "apikeys.noKeys": "API 키가 없습니다. 위에서 하나를 만드세요.",
    "apikeys.created": "생성일:",
    "apikeys.lastUsed": "마지막 사용:",
    "apikeys.delete": "삭제",
    "apikeys.newKey": "새 API 키 (지금 복사하세요, 다시 표시되지 않습니다):",
    "apikeys.dismiss": "닫기",
    # Scan
    "scanPage.title": "도메인 스캐너",
    "scanPage.desc": "원하는 조건에 맞는 사용 가능한 도메인을 찾으세요",
    "scanPage.config": "스캔 구성",
    "scanPage.startScan": "스캔 시작",
    "scanPage.scanning": "스캔 중...",
    "scanPage.progress": "스캔 진행 상황",
    "scanPage.noResults": "스캔 결과 없음",
    "scanPage.recentScans": "최근 스캔",
    "scanPage.scan": "스캔",
    # Appraise
    "appraisePage.badge": "16차원 엔진",
    "appraisePage.title": "도메인 평가",
    "appraisePage.placeholder": "도메인을 입력하세요 (예: techstart.com)",
    "appraisePage.analyzing": "분석 중...",
    "appraisePage.button": "평가",
    "appraisePage.devMode": "개발 모드 — 무제한",
    "appraisePage.loading": "로딩 중...",
    "appraisePage.error": "오류",
    "appraisePage.estimatedValue": "추정 가치",
    "appraisePage.analysis": "16차원 분석",
    "appraisePage.fullAccess": "전체 접근",
    "appraisePage.unlocked": "3/16 잠금 해제",
    "appraisePage.aboveAvg": "평균 이상",
    "appraisePage.belowAvg": "평균 이하",
    "appraisePage.avg": "평균",
    "appraisePage.viewPricing": "가격 보기",
    "appraisePage.recentAppraisals": "최근 평가",
    "appraisePage.limitTitle": "일일 한도 도달",
    "appraisePage.createAccount": "계정 만들기",
    "appraisePage.goBack": "돌아가기",
    "appraisePage.redirecting": "리디렉션 중...",
    "appraisePage.redirectDesc": "계정 생성 페이지로 이동합니다.",
    "appraisePage.modules.0": "등록 데이터 (RDAP)",
    "appraisePage.modules.1": "TLD 프리미엄 등급",
    "appraisePage.modules.2": "도메인 길이",
    "appraisePage.modules.3": "단어 수",
    "appraisePage.modules.4": "발음 가능성",
    "appraisePage.modules.5": "단어 분할",
    "appraisePage.modules.6": "키워드 인기",
    "appraisePage.modules.7": "상업적 의도 (CPC)",
    "appraisePage.modules.8": "검색 결과",
    "appraisePage.modules.9": "크로스 TLD 등록",
    "appraisePage.modules.10": "상표 확인",
    "appraisePage.modules.11": "도메인 권위",
    "appraisePage.modules.12": "브랜더빌리티 점수",
    # Tools scanner
    "tools.scanner.badge": "SEO 스캐너",
    "tools.scanner.title": "SEO 스캐너",
    "tools.scanner.placeholder": "스캔할 도메인 입력",
    "tools.scanner.scanButton": "지금 스캔",
    "tools.scanner.scanningButton": "스캔 중...",
    "tools.scanner.limitsTitle": "스캔 제한",
    "tools.scanner.howItWorks.title": "작동 방식",
    "tools.scanner.features.title": "얻을 수 있는 것",
    "tools.scanner.included.title": "포함 내용",
    "tools.scanner.included.cta": "더 깊은 분석이 필요하세요? 확장 인사이트를 시도해 보세요 →",
    "tools.scanner.cta.pricing": "가격 보기",
    "tools.scanner.cta.extended": "확장 인사이트 보기",
    # Tools lookup
    "tools.lookup.badge": "무료 도구",
    "tools.lookup.title": "도메인 조회",
    "tools.lookup.lookupButton": "조회",
    "tools.lookup.searchingButton": "검색 중...",
    "tools.lookup.loading": "도메인 데이터 가져오는 중...",
    "tools.lookup.whoisTitle": "WHOIS 정보",
    "tools.lookup.dnsTitle": "DNS 레코드",
    "tools.lookup.empty.title": "도메인을 입력하여 시작하세요",
    # Tools insights
    "tools.insights.badge": "프리미엄",
    "tools.insights.title": "확장 인사이트",
    "tools.insights.cta": "확장 인사이트 받기",
    "tools.insights.revealTitle": "공개 가격",
    "tools.insights.reportTitle": "리포트에 포함된 내용",
    "tools.insights.useCasesTitle": "확장 인사이트 사용 시점",
    "tools.insights.ctaTitle": "도메인 인텔리전스 잠금 해제",
    "tools.insights.startFreeTrial": "무료 체험 시작",
    "tools.insights.tryLookup": "먼저 도메인 조회 시도",
    # Tools bulk
    "tools.bulk.badge": "엔터프라이즈",
    "tools.bulk.title": "대량 분석기",
    "tools.bulk.cta": "대량 접근 받기",
    "tools.bulk.statLabel": "배치당 도메인 수",
    "tools.bulk.howItWorks.title": "작동 방식",
    "tools.bulk.outputTitle": "출력 열",
    "tools.bulk.priorityTitle": "우선순위 점수 분석",
    "tools.bulk.customTitle": "사용자 정의 스코어링",
    "tools.bulk.ctaTitle": "도메인 연구를 확장할 준비가 되셨나요?",
    "tools.bulk.startTrial": "엔터프라이즈 체험 시작",
    "tools.bulk.tryLookup": "단일 도메인 조회 시도",
    # Tools api
    "tools.api.badge": "개발자",
    "tools.api.title": "API 인터페이스",
    "tools.api.getKey": "API 키 받기",
    "tools.api.readDocs": "문서 읽기",
    "tools.api.buildTitle": "빌드할 수 있는 것",
    "tools.api.featuresTitle": "API 기능",
    "tools.api.ctaTitle": "빌드할 준비가 되셨나요?",
    "tools.api.viewDocs": "API 문서 보기",
    # Tools trademark
    "tools.trademark.badge": "프리미엄",
    "tools.trademark.title": "상표 모니터",
    "tools.trademark.cta": "모니터링 시작",
    "tools.trademark.severityTitle": "위협 심각도 수준",
    "tools.trademark.problemTitle": "문제점",
    "tools.trademark.solutionTitle": "우리의 솔루션",
    "tools.trademark.howItWorks.title": "작동 방식",
    "tools.trademark.useCasesTitle": "사용 사례",
    "tools.trademark.pricingTitle": "가격",
    "tools.trademark.popular": "인기",
    "tools.trademark.ctaTitle": "지금 브랜드를 보호하세요",
    "tools.trademark.startFreeTrial": "무료 체험 시작",
    "tools.trademark.tryLookup": "도메인 조회 시도",
    "tools.trademark.runScan": "SEO 스캔 실행",
    # Tools database
    "tools.database.badge": "포괄적 데이터",
    "tools.database.statValue": "2,847",
    "tools.database.statLabel": "모든 레지스트리에서 추적되는 TLD",
    "tools.database.methodsTitle": "검색 방법",
    "tools.database.sourcesTitle": "데이터 소스",
    "tools.database.levelsTitle": "접근 수준",
    "tools.database.popular": "인기",
    "tools.database.ctaTitle": "완전한 도메인 데이터베이스에 접근",
    "tools.database.startFreeTrial": "무료 체험 시작",
    "tools.database.tryLookup": "도메인 조회 시도",
    "tools.database.viewDocs": "API 문서 보기",
    # Marketplace main
    "mp.main.badge": "마켓플레이스",
    "mp.main.title": "프리미엄 도메인",
    "mp.main.nameHidden": "이름 숨김",
    "mp.main.revealName": "이름 공개",
    "mp.main.cta.curated": "큐레이션 둘러보기",
    "mp.main.cta.luck": "행운 시도",
    "mp.main.modal.title": "계정 만들기",
    "mp.main.modal.signup": "무료 가입",
    "mp.main.modal.later": "나중에 하기",
    # Marketplace sell
    "mp.sell.badge": "마켓플레이스",
    "mp.sell.title": "도메인 판매",
    "mp.sell.steps.0": "제출",
    "mp.sell.steps.1": "가격 설정",
    "mp.sell.steps.2": "게시",
    "mp.sell.fees.title": "요금 구조",
    "mp.sell.fees.listing.title": "등록 수수료",
    "mp.sell.fees.commission.title": "수수료 요율",
    "mp.sell.eligibility.title": "자격 요건 체크리스트",
    "mp.sell.tools.title": "판매자 도구",
    "mp.sell.cta.title": "판매할 준비가 되셨나요?",
    "mp.sell.cta.signup": "계정 만들기",
    "mp.sell.cta.pricing": "가격 보기",
    # Marketplace luck
    "mp.luck.badge": "마켓플레이스",
    "mp.luck.title": "행운 시도",
    "mp.luck.step1": "1단계: TLD 선택",
    "mp.luck.spinning": "회전 중...",
    "mp.luck.step2": "2단계: 상자 선택",
    "mp.luck.clickToReveal": "클릭하여 공개",
    "mp.luck.howItWorks.title": "작동 방식",
    "mp.luck.cta.marketplace": "마켓플레이스 보기",
    "mp.luck.cta.signup": "무료 가입",
    "mp.luck.modal.title": "계정 만들기",
    "mp.luck.modal.signup": "무료 가입",
    "mp.luck.modal.later": "나중에 하기",
    # Marketplace curated
    "mp.curated.badge": "마켓플레이스",
    "mp.curated.title": "큐레이션 도메인",
    "mp.curated.tryLuck": "행운 시도",
    "mp.curated.howItWorks.title": "작동 방식",
    "mp.curated.cta.marketplace": "마켓플레이스 보기",
    "mp.curated.cta.luck": "행운 시도",
    # Marketplace unmasking
    "mp.unmasking.badge": "마켓플레이스",
    "mp.unmasking.title": "공개 메커니즘 작동 방식",
    "mp.unmasking.vault.title": "볼트 보호",
    "mp.unmasking.howItWorks.title": "작동 방식",
    "mp.unmasking.cta.marketplace": "마켓플레이스 둘러보기",
    "mp.unmasking.cta.luck": "행운 시도",
    # Solutions
    "sol.index.title": "모든 도메인 필요를 위한 솔루션",
    "sol.index.cta.ready": "준비되셨나요?",
    "sol.index.cta.signup": "무료 계정 만들기",
    "sol.index.learnMore": "자세히 보기 →",
    "sol.investors.badge": "투자자를 위한",
    "sol.investors.title": "도메인 투자 수익 극대화",
    "sol.investors.toolsTitle": "투자자를 위한 도구",
    "sol.investors.gettingStarted.title": "시작하기",
    "sol.investors.ctaTitle": "더 스마트하게 플리핑 시작",
    "sol.investors.ctaSignup": "무료 계정 만들기",
    "sol.investors.ctaMarketplace": "마켓플레이스 둘러보기",
    "sol.founders.badge": "창업자를 위한",
    "sol.founders.title": "올바른 도메인으로 브랜드 구축",
    "sol.founders.builtForTitle": "창업자를 위해 구축",
    "sol.founders.ctaTitle": "브랜드 도메인 찾기",
    "sol.founders.ctaSignup": "무료 계정 만들기",
    "sol.founders.ctaAppraise": "평가 도구 시도",
    "sol.agencies.badge": "대행사를 위한",
    "sol.agencies.title": "고객을 위한 도메인 인수 확장",
    "sol.agencies.whyTitle": "대행사가 Ceche를 선택하는 이유",
    "sol.agencies.plansTitle": "모든 대행사를 위한 플랜",
    "sol.agencies.plansDesc": "독립 컨설턴트부터 풀서비스 대행사까지 확장",
    "sol.agencies.ctaTitle": "대행사를 확장할 준비가 되셨나요?",
    "sol.agencies.ctaSignup": "무료 계정 만들기",
    "sol.agencies.ctaApi": "API 문서",
    "sol.available.statLabel": "동시 스캔 TLD",
    "sol.available.title": "초고속 사용 가능한 도메인 검색",
    "sol.available.discovery.title": "스마트 도메인 발견",
    "sol.available.discovery.cta": "무료 검색 시작",
    "sol.available.timeline.title": "도메인을 놓치지 마세요",
    "sol.available.plansTitle": "플랜 선택",
    "sol.available.popular": "인기",
    "sol.available.getStarted": "시작하기",
    "sol.available.bulk.badge": "엔터프라이즈 기능",
    "sol.available.bulk.title": "대량 도메인 스캐너",
    "sol.available.ctaTitle": "완벽한 도메인 찾기",
    "sol.available.ctaSignup": "무료 계정 만들기",
    "sol.available.ctaScan": "SEO 스캐너 시도",
    "sol.research.title": "인수 전 심층 도메인 분석",
    "sol.research.compareTitle": "Ceche 비교",
    "sol.research.ctaTitle": "더 스마트하게 리서치",
    "sol.research.ctaSignup": "무료 계정 만들기",
    "sol.research.ctaAppraise": "평가 도구 시도",
    "sol.premium.heroTitle": "자신감 있게 프리미엄 도메인 인수",
    "sol.premium.pricingTitle": "투명한 가격",
    "sol.premium.pricingDesc": "숨겨진 비용 없음. 표시된 가격이 바로 지불하는 가격입니다.",
    "sol.premium.ctaTitle": "지금 프리미엄 도메인 구매",
    "sol.premium.ctaMarketplace": "마켓플레이스 둘러보기",
    "sol.premium.ctaPricing": "가격 보기",
    # Resources
    "res.index.title": "리소스",
    "res.index.subtitle": "학습 및 지원 받기",
    "res.blog.badge": "Ceche 블로그",
    "res.blog.title": "도메인 인텔리전스 디코딩.",
    "res.blog.topicsBadge": "주제",
    "res.blog.cta.ebooks": "전자책 둘러보기 →",
    "res.blog.cta.pricing": "가격 보기",
    "res.ebooks.badge": "Ceche 전자책",
    "res.ebooks.title": "도메인 투자 심층 분석",
    "res.ebooks.getCopy": "무료 사본 받기",
    "res.ebooks.cta.blog": "블로그 읽기",
    "res.ebooks.cta.pricing": "가격 보기",
    "res.cases.badge": "사례 연구",
    "res.cases.title": "실제 투자자. 실제 결과.",
    "res.cases.cta.contact": "문의하기 →",
    # Company
    "company.about.badge": "Ceche 소개",
    "company.about.title": "데이터 기반 투자를 위해 구축",
    "company.about.cta.0": "평가 시도 →",
    "company.about.cta.1": "마켓플레이스 둘러보기",
    "company.about.origin.badge": "우리의 기원",
    "company.about.origin.title": "시장에 더 나은 데이터가 필요하다는 것을 발견한 도메인 투자자가 설립",
    "company.about.founder.label": "창립자",
    "company.about.values.badge": "우리의 신념",
    "company.about.values.title": "모든 결정을 이끄는 세 가지 원칙",
    "company.about.values.items.0.title": "투명성",
    "company.about.values.items.1.title": "데이터 엄격성",
    "company.about.values.items.2.title": "속도",
    "company.about.cta.title": "다음 도메인을 찾을 준비가 되셨나요?",
    "company.about.cta.marketplace": "마켓플레이스 둘러보기 →",
    "company.about.cta.pricing": "가격 보기",
    "company.affiliates.badge": "Ceche 파트너",
    "company.affiliates.title": "도메인 투자자를 추천하여 수익 창출",
    "company.affiliates.timeline.0": "가입",
    "company.affiliates.timeline.1": "링크 공유",
    "company.affiliates.timeline.2": "30% 수익",
    "company.affiliates.cta.title": "지금 수익 창출 시작",
    "company.affiliates.cta.join": "파트너 프로그램 참여 →",
    "company.affiliates.cta.pricing": "가격 보기",
    "company.affiliates.cta.support": "지원 문의",
    # Help overview
    "helpOverview.badge": "도움말 센터",
    "helpOverview.title": "어떻게 도와드릴까요.",
    "helpOverview.desc": "모든 Ceche 도구에 대한 문서, FAQ 및 지원을 찾아보세요. 사이드바를 사용하여 섹션 간에 이동하세요.",
    "helpOverview.sections.0.title": "문서",
    "helpOverview.sections.1.title": "API 참조",
    "helpOverview.sections.2.title": "자주 묻는 질문",
    "helpOverview.sections.3.title": "문의하기",
    "helpOverview.sections.4.title": "변경 로그",
    # Help docs
    "helpDocs.badge": "문서",
    "helpDocs.title1": "모든 도구,",
    "helpDocs.title2": "문서화됨.",
    "helpDocs.tiersTitle": "구독 등급",
    "helpDocs.needHelp.badge": "도움이 필요하신가요?",
    "helpDocs.needHelp.title": "Premium 구독자는 4시간 지원을 받습니다",
    "helpDocs.needHelp.cta": "지원 문의",
    "helpDocs.openTool": "도구 열기",
    # Help FAQ
    "helpFaq.badge": "자주 묻는 질문",
    "helpFaq.title1": "자주",
    "helpFaq.title2": "묻는 질문.",
    "helpFaq.stillQuestions": "아직 질문이 있으신가요?",
    "helpFaq.supportTeam": "지원팀이 도와드리겠습니다",
    "helpFaq.contactSupport": "지원 문의",
    "helpFaq.sections.0.title": "시작하기",
    "helpFaq.sections.1.title": "가격 및 결제",
    "helpFaq.sections.2.title": "도구",
    "helpFaq.sections.3.title": "API 및 통합",
    "helpFaq.sections.4.title": "계정 및 지원",
    # Help API
    "helpApi.badge": "API 문서",
    "helpApi.title1": "Ceche와 함께",
    "helpApi.title2": "빌드하기.",
    "helpApi.baseUrl": "기본 URL",
    "helpApi.auth": "인증",
    "helpApi.endpoints": "엔드포인트",
    "helpApi.rateLimits": "속도 제한",
    "helpApi.enterprise.badge": "엔터프라이즈",
    "helpApi.enterprise.title": "매일 10,000회 API 호출",
    "helpApi.enterprise.cta": "API 키 받기",
    "helpApi.openTool": "도구 열기",
    # Help contact
    "helpContact.badge": "문의하기",
    "helpContact.title1": "연락",
    "helpContact.title2": "주세요.",
    "helpContact.form.name": "이름",
    "helpContact.form.namePlaceholder": "귀하의 이름",
    "helpContact.form.email": "이메일",
    "helpContact.form.subject": "제목",
    "helpContact.form.message": "메시지",
    "helpContact.form.send": "메시지 보내기",
    "helpContact.channels.title": "기타 연락 채널",
    "helpContact.responseTimes.title": "응답 시간",
    "helpContact.businessHours.title": "영업 시간",
    # Help changelog
    "helpChangelog.badge": "변경 로그",
    "helpChangelog.title1": "모든 커밋,",
    "helpChangelog.title2": "기록됨.",
    "helpChangelog.desc": "모든 업데이트는 git 히스토리에서 직접 가져옵니다. 실제 커밋, 실제 날짜, 실제 설명.",
    "helpChangelog.comingSoon.badge": "출시 예정",
    "helpChangelog.comingSoon.title": "경매 추적, 모바일 앱, ML 밸류에이션",
    "helpChangelog.comingSoon.cta": "로드맵 보기",
    # Misc
    "mp.main.modal.redirecting": "가입 페이지로 리디렉션 중, {count}초 후...",
    "appraisePage.extendedInsightsCta": "확장 인사이트",
    "scanPage.noResultsDesc": "스캔 설정을 구성하고 \"스캔 시작\"을 클릭하여 사용 가능한 도메인을 찾으세요.",
}

skipped = 0
for path, value in korean.items():
    try:
        set_nested(ko, path, value)
    except (KeyError, IndexError, TypeError) as e:
        print(f"SKIP {path}: {e}")
        skipped += 1

with open('messages/ko.json', 'w', encoding='utf-8') as f:
    json.dump(ko, f, ensure_ascii=False, indent=2)

# Count Korean strings
def count_korean(obj):
    count = 0
    if isinstance(obj, dict):
        for v in obj.values():
            count += count_korean(v)
    elif isinstance(obj, list):
        for v in obj:
            count += count_korean(v)
    elif isinstance(obj, str) and obj and len(obj) > 3:
        has_korean = any('\uac00' <= c <= '\ud7af' for c in obj)
        if has_korean:
            count += 1
    return count

korean_count = count_korean(ko)
print(f"Done! {len(korean)} translations applied, {skipped} skipped, {korean_count} Korean strings in ko.json.")
