import json
import re

with open('messages/zh.json', 'r') as f:
    zh = json.load(f)

with open('messages/ko.json', 'r') as f:
    ko = json.load(f)

# Korean translations for ALL Chinese strings from zh.json
# Organized by section for clarity
korean_translations = {
    # ==================== HOME ====================
    "home.hero.subtitle": "모든 목록은 전체 통계를 표시합니다 — 추정 가치, 건강 점수, CPC, 브랜더빌리티 — 그러나 이름은 공개 비용을 지불할 때까지 숨겨집니다. 경매 인플레이션 없음. 스나이핑 없음.",
    "home.searchTool.description": "위 검색 창에 도메인을 입력하세요. 사용 가능 여부, 가치, 구축할 수 있는 것을 알려드립니다. 가입 불필요.",
    "home.searchTool.taken.desc": "WHOIS 세부 정보를 표시합니다 — 소유자, 만료일, 등록 기관, 네임서버 정보. 아웃리치 또는 만료 대기에 유용합니다.",
    "home.searchTool.available.desc": "프리미엄, 중간, 저 등급으로 평가합니다 — 혼란스러운 점수 없이 명확한 레이블. 이름으로 구축할 수 있는 것에 대한 제안과 전체 16차원 평가를 실행하는 버튼도 포함됩니다.",
    "home.searchTool.appraise.desc": "\"이 이름을 평가\"를 클릭하여 전체 16차원 분석을 수행합니다 — 발음 가능성, 상표 위험, 과거 DNS, 브랜더빌리티 점수 및 추정 가치 범위.",
    "home.builtFor.investors.desc": "수천 가지 단어 조합을 스캔하고, 초안 목록을 몇 초 만에 평가하며, 시장이 발견하기 전에 저평가된 이름을 발견합니다. 스캐너는 사용 가능한 모든 이름에 DA, 스팸 점수 및 백링크 프로필을 표시합니다.",
    "home.builtFor.founders.desc": "말하기 쉽고, 철자하기 쉽고, 사용하기 안전한 이름을 찾으세요. 16차원 엔진은 브랜드를 커밋하기 전에 발음 가능성, 상표 충돌 및 브랜더빌리티를 확인합니다.",
    "home.builtFor.agencies.desc": "권위와 깨끗한 백링크를 보유한 만료된 도메인을 찾으세요. 스캐너는 DA, 스팸 점수 및 색인 상태를 표시하여 기존 SEO 가치부터 시작할 수 있게 합니다.",
    "home.marketplace.desc1": "모든 목록은 전체 인텔리전스를 표시합니다 — 추정 가치, 건강 점수, CPC, 브랜더빌리티, TLD 및 키워드 의도 — 이름 자체를 제외한 모든 것. 힌트 없음. 부분 공개 없음. 별표 없음.",
    "home.marketplace.desc2": "공개 마켓플레이스는 프리미엄 이름이 나타나는 즉시 스크래핑됩니다. Ceche는 이름을 숨기고 대신 인텔리전스를 표시합니다 — 따라서 가치가 아니라 가시성이 거래를 주도합니다. 통계를 잘 읽는 투자자는 경매 열기가 가격을 올리기 전에 항상 이름을 발견합니다.",
    "home.howItWorks.step1.desc": ".com($79), .net($39), .io($29), .co($9)를 선택하세요. 또는 선택을 건너뛰고 모든 TLD에 대해 균일 가격 $19를 지불하세요.",
    "home.howItWorks.step2.desc": "세 개의 닫힌 상자가 회전하는 애니메이션과 함께 나타납니다. 각각 고유한 프리미엄 도메인을 포함합니다. 멈추면 하나를 선택하세요.",
    "home.howItWorks.step3.desc": "도메인이 즉시 공개됩니다. 귀하에게만 독점적으로 잠깁니다 — 다른 사람은 구매할 수 없습니다. 선호하는 등록 기관에서 즉시 등록하세요.",
    "home.underTheHood.description": "모든 도메인 이름은 저장 시 암호화됩니다. 모든 스캔은 실제 인프라에서 실행됩니다. 지름길 없음.",
    "home.underTheHood.goroutine.desc": "스캐너는 50개의 동시 고루틴을 실행하며, 각각 5초 타임아웃으로 DNS 레코드를 확인합니다. 결과는 한 번에 100개씩 배치 삽입됩니다. TLD별 속도 제한을 준수합니다.",
    "home.underTheHood.encryption.desc": "데이터베이스의 모든 도메인 이름은 AES-256-GCM으로 암호화됩니다. 누군가 전체 DB 덤프를 얻더라도 쓰레기만 보게 됩니다 — 검색 기록이 아닙니다.",
    "home.underTheHood.caching.desc": "반복 쿼리는 1시간 TTL의 제로 비용 bigcache에 히트됩니다. 전체 16차원 분석을 다시 실행하지 않고도 평가 결과가 빠르게 유지됩니다.",
    "home.faq.items.0.question": "무료 평가는 몇 번 받을 수 있나요?",
    "home.faq.items.0.answer": "가입하지 않으면 하루에 3번의 평가를 받습니다. 무료 가입하면 하루에 12번. Premium 스타트업($79/월)은 하루 30번, Premium 엔터프라이즈($129/월)는 무제한.",
    "home.faq.items.1.question": "이름 검색과 평가의 차이점은 무엇인가요?",
    "home.faq.items.1.answer": "이름 검색은 무료이며 즉시 — 도메인 사용 가능 여부를 알려주고, 등록된 경우 WHOIS를 표시하며, 사용 가능한 경우 프리미엄/중간/저 등급으로 평가합니다. 평가는 발음 가능성, 상표 위험, 브랜더빌리티 및 추정 가치를 점수화하는 심층 16차원 분석입니다.",
    "home.faq.items.2.question": "행운 시도는 어떻게 작동하나요?",
    "home.faq.items.2.answer": "TLD(.com, .net, .io, .co)를 선택하고 TLD별 가격을 지불하세요. 세 개의 닫힌 상자가 회전하는 애니메이션과 함께 나타납니다. 멈추면 하나를 선택하세요. 고유한 프리미엄 도메인이 즉시 공개됩니다. 잠깁니다 — 다른 사람은 구매할 수 없습니다. 또는 TLD 선택 없이 균일 가격 $19를 지불하세요.",
    "home.faq.items.3.question": "도메인 이름 공개 후에 어떻게 되나요?",
    "home.faq.items.3.answer": "공개 후 도메인은 평가할 수 있습니다. Dynadot, Namecheap 또는 Porkbun에서 등록하는 직접 링크를 표시합니다. 등록할 위치를 선택합니다 — 특정 등록 기관에 잠그지 않습니다.",
    "home.faq.items.4.question": "Premium 구독에 무엇이 포함되나요?",
    "home.faq.items.4.answer": "Premium 스타트업($79/월)은 하루 30번의 평가와 도메인 스캐너(DA, 스팸, 백링크), 확장 인사이트(USPTO/WIPO, 상표 역사), 대량 도메인 감사를 제공합니다. 엔터프라이즈($129/월)는 무제한 평가, API 접근 및 우선 지원을 추가합니다.",
    "home.faq.items.5.question": "Ceche에서 도메인을 판매할 수 있나요?",
    "home.faq.items.5.answer": "네. 마켓플레이스에 프리미엄 도메인을 등록하세요. 평가 후 가격을 설정합니다. 표준 등록 $5, 우선 배치 $10. 성공적인 판매에 대해 판매 가격에 따라 8-15%의 수수료를 부과합니다.",
    "home.faq.items.6.question": "검색 데이터가 안전한가요?",
    "home.faq.items.6.answer": "네. 검색한 도메인 이름은 저장 전에 AES-256-GCM으로 암호화됩니다. 검색 데이터를 판매하거나 공유하지 않습니다. 경쟁사가 귀하가 보고 있는 것을 보지 못합니다.",
    "home.worldMap.description": "9개 언어와 4개 TLD에 걸친 도메인 투자자, 스타트업 창업자 및 SEO 대행사를 위한 실시간 인텔리전스.",
    "home.cta.description": "하루 3번의 무료 평가로 시작하세요. 신용 카드 불필요.",
    # ==================== PRICING ====================
    "pricingPage.plans.free.description": "기본 도구로 시작하세요. 신용 카드 불필요.",
    "pricingPage.plans.free.features.0": "하루 3번의 평가 (미가입)",
    "pricingPage.plans.free.features.1": "하루 12번의 평가 (가입 후)",
    "pricingPage.plans.free.features.2": "이름 검색 도구",
    "pricingPage.plans.free.features.3": "기본 WHOIS 조회",
    "pricingPage.plans.free.features.4": "도메인 스캐너 (DA, 스팸, 백링크)",
    "pricingPage.plans.free.features.5": "확장 인사이트 (USPTO/WIPO)",
    "pricingPage.plans.free.features.6": "대량 도메인 감사",
    "pricingPage.plans.free.features.7": "API 접근",
    "pricingPage.plans.startup.description": "소규모 팀과 진지한 도메인 투자자를 위한.",
    "pricingPage.plans.startup.features.0": "하루 30번의 평가",
    "pricingPage.plans.startup.features.1": "이름 검색 도구",
    "pricingPage.plans.startup.features.2": "도메인 스캐너 (DA, 스팸, 백링크)",
    "pricingPage.plans.startup.features.3": "확장 인사이트 (USPTO/WIPO)",
    "pricingPage.plans.startup.features.4": "대량 도메인 감사",
    "pricingPage.plans.startup.features.5": "우선 마켓플레이스 목록",
    "pricingPage.plans.startup.features.6": "API 접근",
    "pricingPage.plans.startup.features.7": "우선 지원",
    "pricingPage.plans.enterprise.description": "대행사, 전문가 및 고급 사용자를 위한.",
    "pricingPage.plans.enterprise.features.0": "무제한 평가",
    "pricingPage.plans.enterprise.features.1": "이름 검색 도구",
    "pricingPage.plans.enterprise.features.2": "도메인 스캐너 (DA, 스팸, 백링크)",
    "pricingPage.plans.enterprise.features.3": "확장 인사이트 (USPTO/WIPO)",
    "pricingPage.plans.enterprise.features.4": "대량 도메인 감사",
    "pricingPage.plans.enterprise.features.5": "우선 마켓플레이스 목록",
    "pricingPage.plans.enterprise.features.6": "전체 API 접근",
    "pricingPage.plans.enterprise.features.7": "우선 지원",
    "pricingPage.tryYourLuck.subtitle": "TLD를 선택하고, 3개 상자를 돌려, 귀하에게만 독점적으로 잠긴 프리미엄 도메인을 공개하세요.",
    "pricingPage.fees.reveal.description": "표준 목록은 이름이 숨겨진 상태로 통계를 표시합니다. 도메인 이름을 보려면 일회성 공개 수수료를 지불하세요.",
    "pricingPage.fees.reveal.rows.0.tier": "저",
    "pricingPage.fees.reveal.rows.0.range": "$500 미만",
    "pricingPage.fees.reveal.rows.1.tier": "중",
    "pricingPage.fees.reveal.rows.1.range": "$500 – $5,000",
    "pricingPage.fees.reveal.rows.2.tier": "고",
    "pricingPage.fees.reveal.rows.2.range": "$5,001 – $50,000",
    "pricingPage.fees.reveal.rows.3.tier": "프리미엄",
    "pricingPage.fees.reveal.rows.3.range": "$50,001+",
    "pricingPage.compare.subtitle": "Ceche가 기존 도메인 플랫폼과 어떻게 비교되는지 알아보세요.",
    "pricingPage.compare.rows.0": "AI 도메인 밸류에이션",
    "pricingPage.compare.rows.1": "16차원 스코어링",
    "pricingPage.compare.rows.2": "WHOIS + DNS 인텔리전스",
    "pricingPage.compare.rows.3": "SEO/DA/스팸 스캔",
    "pricingPage.compare.rows.4": "대량 도메인 감사",
    "pricingPage.compare.rows.5": "상표 모니터링",
    "pricingPage.compare.rows.6": "마켓플레이스 공개 모델",
    "pricingPage.compare.rows.7": "API 접근",
    "pricingPage.compare.rows.8": "무료 티어",
    "pricingPage.cta.description": "몇 초 만에 무료 계정을 만드세요. 신용 카드 불필요.",
    # ==================== TOOLS SCANNER ====================
    "tools.scanner.description": "DA, 스팸 점수, 백링크 프로필 및 색인 상태를 포함한 도메인 및 SEO 감사. 어떤 도메인의 검색 엔진 건강에 대한 즉각적인 인사이트를 얻으세요.",
    "tools.scanner.limits.0.plan": "스타트업",
    "tools.scanner.limits.0.scans": "하루 30번",
    "tools.scanner.limits.0.price": "$79/월",
    "tools.scanner.limits.1.plan": "엔터프라이즈",
    "tools.scanner.limits.1.scans": "무제한",
    "tools.scanner.limits.1.price": "$129/월",
    "tools.scanner.howItWorks.steps.0.title": "도메인 입력",
    "tools.scanner.howItWorks.steps.0.desc": "위 검색 창에 도메인 이름을 입력하세요.",
    "tools.scanner.howItWorks.steps.1.title": "분석 실행",
    "tools.scanner.howItWorks.steps.1.desc": "엔진이 도메인 건강의 16개 차원을 즉시 스캔합니다.",
    "tools.scanner.howItWorks.steps.2.title": "보고서 받기",
    "tools.scanner.howItWorks.steps.2.desc": "상세한 SEO 지표, 백링크 데이터 및 스팸 점수를 확인하세요.",
    "tools.scanner.features.items.0.title": "도메인 권위 및 페이지 권위",
    "tools.scanner.features.items.0.desc": "도메인 강도의 과거 트렌드를 보여주는 DA 및 PA 지표.",
    "tools.scanner.features.items.1.title": "백링크 프로필",
    "tools.scanner.features.items.1.desc": "인용 도메인 및 앵커 텍스트 분포를 포함한 완전한 백링크 분석.",
    "tools.scanner.features.items.2.title": "스팸 점수",
    "tools.scanner.features.items.2.desc": "패널티 위험 평가 및 권장 사항을 포함한 머신 러닝 스팸 감지.",
    "tools.scanner.features.items.3.title": "색인 상태",
    "tools.scanner.features.items.3.desc": "Google, Bing 및 Yandex에서의 검색 엔진 색인 확인.",
    "tools.scanner.features.items.4.title": "기술 SEO",
    "tools.scanner.features.items.4.desc": "Core Web Vitals, 모바일 친화성 및 구조화된 데이터 분석.",
    "tools.scanner.features.items.5.title": "경쟁사 분석",
    "tools.scanner.features.items.5.desc": "귀하의 틈새 시장에서 상위 경쟁사와 도메인 지표를 비교하세요.",
    "tools.scanner.included.items.0": "과거 트렌드가 포함된 DA 및 PA 지표",
    "tools.scanner.included.items.1": "인용 도메인이 포함된 완전한 백링크 분석",
    "tools.scanner.included.items.2": "패널티 위험 평가가 포함된 머신 러닝 스팸 감지",
    "tools.scanner.included.items.3": "Google, Bing 및 Yandex에서의 검색 엔진 색인 확인",
    "tools.scanner.included.items.4": "Core Web Vitals, 모바일 친화성 및 구조화된 데이터 분석",
    "tools.scanner.included.items.5": "귀하의 틈새 시장에서 상위 도메인과의 경쟁사 비교",
    "tools.scanner.cta.title": "더 깊은 분석이 필요하신가요?",
    "tools.scanner.cta.description": "과거 데이터, 대량 스캔 및 API 통합에 접근하려면 업그레이드하세요.",
    # ==================== TOOLS LOOKUP ====================
    "tools.lookup.description": "모든 도메인에 대한 즉각적인 WHOIS 데이터, DNS 레코드 및 등록 세부 정보. 몇 초 만에 필요한 인텔리전스를 얻으세요.",
    "tools.lookup.placeholder": "도메인 입력 (예: example.com)",
    "tools.lookup.dnsHeaders.0": "유형",
    "tools.lookup.dnsHeaders.1": "이름",
    "tools.lookup.dnsHeaders.2": "값",
    "tools.lookup.dnsHeaders.3": "TTL",
    "tools.lookup.whoisLabels.0": "도메인",
    "tools.lookup.whoisLabels.1": "등록 기관",
    "tools.lookup.whoisLabels.2": "등록일",
    "tools.lookup.whoisLabels.3": "만료일",
    "tools.lookup.whoisLabels.4": "마지막 업데이트",
    "tools.lookup.whoisLabels.5": "네임서버",
    "tools.lookup.whoisLabels.6": "상태",
    "tools.lookup.whoisLabels.7": "등록 조직",
    "tools.lookup.whoisLabels.8": "국가",
    "tools.lookup.needMore.title": "더 많은 세부 정보가 필요하신가요?",
    "tools.lookup.needMore.description": "확장 인사이트로 과거 데이터, 상표 확인 및 포괄적인 도메인 인텔리전스를 얻으세요.",
    "tools.lookup.needMore.signup": "무료 가입",
    "tools.lookup.needMore.seoScan": "SEO 스캔 실행",
    "tools.lookup.empty.description": "WHOIS 데이터, DNS 레코드 및 등록 세부 정보를 보려면 도메인을 검색하세요.",
    # ==================== TOOLS INSIGHTS ====================
    "tools.insights.description": "포괄적인 도메인 연구를 위한 심층 과거 데이터, DNS 레코드, USPTO/WIPO 상표 확인 및 WHOIS/RDAP 로그.",
    "tools.insights.tiers.0.name": "기본",
    "tools.insights.tiers.0.desc": "표준 도메인 가치",
    "tools.insights.tiers.1.name": "표준",
    "tools.insights.tiers.1.desc": "중간 도메인 가치",
    "tools.insights.tiers.2.name": "프리미엄",
    "tools.insights.tiers.2.desc": "고가치 도메인",
    "tools.insights.tiers.3.name": "엔터프라이즈",
    "tools.insights.tiers.3.desc": "초프리미엄 도메인",
    "tools.insights.pricingNote": "도메인 가치와 복잡성에 기반한 가격",
    "tools.insights.sections.0.title": "과거 데이터",
    "tools.insights.sections.0.desc": "Wayback Machine 스냅샷 및 과거 콘텐츠 변경.",
    "tools.insights.sections.1.title": "DNS 레코드",
    "tools.insights.sections.1.desc": "A, MX, NS, TXT 및 CNAME을 포함한 완전한 DNS 레코드 열거.",
    "tools.insights.sections.2.title": "WHOIS / RDAP",
    "tools.insights.sections.2.desc": "등록 데이터, 도메인 연령, 등록 기관 역사 및 네임서버 변경.",
    "tools.insights.sections.3.title": "상표 확인",
    "tools.insights.sections.3.desc": "USPTO 및 WIPO 상표 데이터베이스 충돌 감지.",
    "tools.insights.sections.4.title": "SSL 인증서",
    "tools.insights.sections.4.desc": "인증 기관, 만료일 및 체인 검증.",
    "tools.insights.sections.5.title": "서버 인텔리전스",
    "tools.insights.sections.5.desc": "호스팅 제공업체, IP 지리적 위치 및 기술 스택 감지.",
    "tools.insights.useCases.0.title": "도메인 인수",
    "tools.insights.useCases.0.desc": "제안하기 전에 도메인 역사를 연구하세요.",
    "tools.insights.useCases.1.title": "상표 클리어런스",
    "tools.insights.useCases.1.desc": "브랜드 출시 전에 충돌을 확인하세요.",
    "tools.insights.useCases.2.title": "경쟁사 분석",
    "tools.insights.useCases.2.desc": "경쟁사의 도메인 전략과 역사를 이해하세요.",
    "tools.insights.useCases.3.title": "포트폴리오 실사",
    "tools.insights.useCases.3.desc": "숨겨진 위험과 기회를 위해 포트폴리오를 감사하세요.",
    "tools.insights.ctaDescription": "확장 인사이트 보고서로 전체 그림을 얻으세요.",
    # ==================== TOOLS BULK ====================
    "tools.bulk.description": "포트폴리오 분석 및 대규모 도메인 연구를 위한 다중 도메인 배치 평가 도구. 몇 초 만에 수천 개의 도메인을 처리합니다.",
    "tools.bulk.stats.0.label": "차원",
    "tools.bulk.stats.1.label": "TLD",
    "tools.bulk.stats.2.label": "도메인당",
    "tools.bulk.howItWorks.steps.0.title": "목록 업로드",
    "tools.bulk.howItWorks.steps.0.desc": "도메인을 붙여넣거나 최대 5,000개 도메인이 포함된 CSV 파일을 업로드하세요.",
    "tools.bulk.howItWorks.steps.1.title": "스코어링 구성",
    "tools.bulk.howItWorks.steps.1.desc": "16개 스코어링 차원 각각에 대해 사용자 정의 가중치를 설정하세요.",
    "tools.bulk.howItWorks.steps.2.title": "처리",
    "tools.bulk.howItWorks.steps.2.desc": "엔진이 우선순위 큐를 사용하여 모든 도메인을 병렬로 평가합니다.",
    "tools.bulk.howItWorks.steps.3.title": "결과 내보내기",
    "tools.bulk.howItWorks.steps.3.desc": "점수, 가격 데이터 및 우선순위 순위가 포함된 CSV를 다운로드하세요.",
    "tools.bulk.outputHeaders.0": "열",
    "tools.bulk.outputHeaders.1": "설명",
    "tools.bulk.outputHeaders.2": "예시",
    "tools.bulk.outputRows.0.0": "도메인",
    "tools.bulk.outputRows.0.1": "분석된 도메인 이름",
    "tools.bulk.outputRows.1.0": "도메인 등급",
    "tools.bulk.outputRows.1.1": "권위 점수 0-100",
    "tools.bulk.outputRows.2.0": "SEO 점수",
    "tools.bulk.outputRows.2.1": "종합 (백링크 40%, 트래픽 30%, 키워드 20%, 기술 10%)",
    "tools.bulk.outputRows.3.0": "구매 의도",
    "tools.bulk.outputRows.3.1": "구매 가능성 0-100 점수",
    "tools.bulk.outputRows.4.0": "우선순위 점수",
    "tools.bulk.outputRows.4.1": "모든 차원의 종합 순위",
    "tools.bulk.outputRows.5.0": "추정 가치",
    "tools.bulk.outputRows.5.1": "공정 시장 가치 범위",
    "tools.bulk.dimensions.0.name": "백링크 프로필",
    "tools.bulk.dimensions.1.name": "트래픽 분석",
    "tools.bulk.dimensions.2.name": "키워드 지표",
    "tools.bulk.dimensions.3.name": "기술 SEO",
    "tools.bulk.customDescription": "특정 사용 사례에 따라 차원 가중치를 조정하세요. SEO 지표, 트래픽 잠재력 또는 구매 의도를 우선시하든 포트폴리오 전략에 맞게 스코어링을 조정할 수 있습니다.",
    "tools.bulk.modes.0.title": "투자자 모드",
    "tools.bulk.modes.0.desc": "트래픽과 가치 중심으로 투자 수익 극대화",
    "tools.bulk.modes.1.title": "개발자 모드",
    "tools.bulk.modes.1.desc": "기술 지표와 권위 우선",
    "tools.bulk.modes.2.title": "브랜드 모드",
    "tools.bulk.modes.2.desc": "상표 안전성과 기억 가능성 강조",
    "tools.bulk.ctaDescription": "엔터프라이즈 접근으로 배치당 최대 5,000개 도메인을 처리하세요.",
    # ==================== TOOLS API ====================
    "tools.api.description": "프로그래밍 방식 도메인 인텔리전스를 위한 RESTful API. 사용자 정의 통합을 구축하고, 워크플로우를 자동화하며, 프로그래밍 방식으로 모든 도메인 데이터에 접근하세요.",
    "tools.api.buildCards.0.title": "도메인 포트폴리오 트래커",
    "tools.api.buildCards.0.desc": "가치 변화, 만료 알림 및 SEO 변화에 대해 포트폴리오를 자동으로 모니터링합니다.",
    "tools.api.buildCards.0.linkText": "도메인 조회 시도",
    "tools.api.buildCards.1.title": "시장 인텔리전스 대시보드",
    "tools.api.buildCards.1.desc": "실시간 도메인 가격, 트렌드 및 경쟁 분석으로 사용자 정의 대시보드를 구축하세요.",
    "tools.api.buildCards.1.linkText": "대량 분석기 탐색",
    "tools.api.buildCards.2.title": "브랜드 보호 시스템",
    "tools.api.buildCards.2.desc": "상표 모니터링을 자동화하고 잠재적 브랜드 충돌에 대한 즉각적인 알림을 받으세요.",
    "tools.api.buildCards.2.linkText": "상표 모니터 보기",
    "tools.api.features.0.title": "RESTful API",
    "tools.api.features.0.desc": "표준 HTTP 메서드로 모든 도메인 인텔리전스 엔드포인트에 완전히 접근.",
    "tools.api.features.1.title": "Webhook",
    "tools.api.features.1.desc": "webhook 콜백을 통한 도메인 변경 및 이벤트에 대한 실시간 알림.",
    "tools.api.features.2.title": "속도 제한",
    "tools.api.features.2.desc": "엔터프라이즈 플랜에서 매일 10,000번의 호출 및 스파이크용 버스트 용량.",
    "tools.api.features.3.title": "SDK",
    "tools.api.features.3.desc": "Python, Node.js, Go 및 Ruby용 공식 라이브러리와 전체 문서.",
    "tools.api.features.4.title": "샌드박스",
    "tools.api.features.4.desc": "라이브 전환 전 개발 및 통합 테스트를 위한 테스트 환경.",
    "tools.api.features.5.title": "문서",
    "tools.api.features.5.desc": "코드 예제, 튜토리얼 및 모범 사례가 포함된 전체 API 참조.",
    "tools.api.ctaDescription": "API 키를 받고 오늘 도메인 인텔리전스 통합을 시작하세요.",
    "tools.api.modal.title": "API 키 받기",
    "tools.api.modal.description": "무료 계정을 만들어 API 키를 받고 도메인 인텔리전스 데이터로 구축을 시작하세요.",
    "tools.api.modal.cta": "무료 계정 만들기",
    "tools.api.modal.back": "돌아가기",
    # ==================== TOOLS TRADEMARK ====================
    "tools.trademark.description": "USPTO/WIPO 충돌 감지 및 알림. 글로벌 데이터베이스에 대한 능동적 상표 모니터링으로 브랜드를 보호하세요.",
    "tools.trademark.levels.0.level": "심각",
    "tools.trademark.levels.0.desc": "직접 상표 충돌 감지",
    "tools.trademark.levels.1.level": "높음",
    "tools.trademark.levels.1.desc": "동일 업계의 유사 상표",
    "tools.trademark.levels.2.level": "중간",
    "tools.trademark.levels.2.desc": "다른 클래스의 유사 이름",
    "tools.trademark.levels.3.level": "낮음",
    "tools.trademark.levels.3.desc": "경미한 유사성, 낮은 위험",
    "tools.trademark.problems.0": "상표 침해 소송 비용은 평균 $100,000 이상",
    "tools.trademark.problems.1": "새 도메인 등록은 매분 발생",
    "tools.trademark.problems.2": "대규모 수동 모니터링은 불가능",
    "tools.trademark.problems.3": "알게 될 때쯤 피해는 이미 발생",
    "tools.trademark.solutions.0": "실시간 USPTO 및 WIPO 데이터베이스 모니터링",
    "tools.trademark.solutions.1": "목록당 최대 5,000개 도메인 스캔",
    "tools.trademark.solutions.2": "이메일 및 webhook을 통한 즉각적인 충돌 알림",
    "tools.trademark.solutions.3": "신뢰 수준이 포함된 위험 스코어링",
    "tools.trademark.howItWorks.steps.0.title": "도메인 추가",
    "tools.trademark.howItWorks.steps.0.desc": "모니터링할 브랜드 도메인 또는 키워드를 업로드하세요.",
    "tools.trademark.howItWorks.steps.1.title": "기준 설정",
    "tools.trademark.howItWorks.steps.1.desc": "업계, 지리적 범위 및 민감도를 정의하세요.",
    "tools.trademark.howItWorks.steps.2.title": "모니터링",
    "tools.trademark.howItWorks.steps.2.desc": "USPTO, EUIPO 및 WIPO 데이터베이스를 지속적으로 스캔합니다.",
    "tools.trademark.howItWorks.steps.3.title": "알림 받기",
    "tools.trademark.howItWorks.steps.3.desc": "잠재적 충돌에 대한 즉각적인 알림을 받으세요.",
    "tools.trademark.useCases.0.title": "브랜드 보호",
    "tools.trademark.useCases.0.content": "모든 주요 TLD에서 사이버스쿼팅, 오타스쿼팅 및 브랜드 사칭을 모니터링합니다.",
    "tools.trademark.useCases.1.title": "제품 출시",
    "tools.trademark.useCases.1.content": "새 제품 출시 또는 새 시장 진출 전에 상표를 클리어링하세요.",
    "tools.trademark.useCases.2.title": "M&A 실사",
    "tools.trademark.useCases.2.content": "인수, 합병 또는 투자 라운드 중 상표 위험을 감사하세요.",
    "tools.trademark.useCases.3.title": "포트폴리오 관리",
    "tools.trademark.useCases.3.content": "도메인 포트폴리오를 상표 문제와 법적 분쟁으로부터 보호하세요.",
    "tools.trademark.plans.0.plan": "무료",
    "tools.trademark.plans.0.features.0": "하루 3번의 미서명 스캔",
    "tools.trademark.plans.0.features.1": "하루 12번의 서명 스캔",
    "tools.trademark.plans.0.features.2": "기본 지표",
    "tools.trademark.plans.1.plan": "스타트업",
    "tools.trademark.plans.1.features.0": "하루 30번의 스캔",
    "tools.trademark.plans.1.features.1": "우선 처리",
    "tools.trademark.plans.1.features.2": "CSV 내보내기",
    "tools.trademark.plans.1.features.3": "이메일 알림",
    "tools.trademark.plans.2.plan": "엔터프라이즈",
    "tools.trademark.plans.2.features.0": "무제한 스캔",
    "tools.trademark.plans.2.features.1": "API 접근 (매일 10K 호출)",
    "tools.trademark.plans.2.features.2": "Webhook 통합",
    "tools.trademark.plans.2.features.3": "전용 지원",
    "tools.trademark.ctaDescription": "늦기 전에 시작하세요. 지금 모니터링을 시작하세요.",
    # ==================== TOOLS DATABASE ====================
    "tools.database.description": "가장 포괄적인 도메인 데이터베이스에 접근하세요. 모든 주요 TLD의 등록, 만료 및 가격을 추적합니다.",
    "tools.database.stats.0.label": "추적 도메인",
    "tools.database.stats.0.desc": "모든 TLD의 활성 등록",
    "tools.database.stats.1.label": "과거 기록",
    "tools.database.stats.1.desc": "등록 및 만료 역사",
    "tools.database.stats.2.label": "일일 업데이트",
    "tools.database.stats.2.desc": "매일 처리되는 새 등록",
    "tools.database.stats.3.label": "가동 시간",
    "tools.database.stats.3.desc": "데이터베이스 가용성 보장",
    "tools.database.methods.0.title": "단일 조회",
    "tools.database.methods.0.desc": "즉각적인 등록 데이터와 사용 가능 상태를 위해 도메인을 검색하세요.",
    "tools.database.methods.1.title": "대량 확인",
    "tools.database.methods.1.desc": "대량 사용 가능 분석을 위해 최대 5,000개 도메인을 한 번에 업로드하세요.",
    "tools.database.methods.2.title": "API 쿼리",
    "tools.database.methods.2.desc": "매일 최대 10,000번의 호출로 RESTful API를 통한 프로그래밍 방식 접근.",
    "tools.database.sources.0.source": "ICANN",
    "tools.database.sources.0.desc": "공식 도메인 등록 데이터",
    "tools.database.sources.1.source": "레지스트리 운영자",
    "tools.database.sources.1.desc": "직접 TLD 영역 파일 접근",
    "tools.database.sources.2.source": "WHOIS/RDAP",
    "tools.database.sources.2.desc": "등록 및 연락처 정보",
    "tools.database.sources.3.source": "Wayback Machine",
    "tools.database.sources.3.desc": "과거 콘텐츠 스냅샷",
    "tools.database.sources.4.source": "인증서 투명성",
    "tools.database.sources.4.desc": "SSL 인증서 모니터링",
    "tools.database.sources.5.source": "DNS 리졸버",
    "tools.database.sources.5.desc": "실시간 DNS 레코드 검증",
    "tools.database.plans.0.plan": "무료",
    "tools.database.plans.0.features.0": "기본 조회",
    "tools.database.plans.0.features.1": "하루 3번의 검색",
    "tools.database.plans.0.features.2": "제한된 TLD",
    "tools.database.plans.1.plan": "스타트업",
    "tools.database.plans.1.features.0": "전체 데이터베이스",
    "tools.database.plans.1.features.1": "하루 30번의 검색",
    "tools.database.plans.1.features.2": "CSV 내보내기",
    "tools.database.plans.1.features.3": "우선 지원",
    "tools.database.plans.2.plan": "엔터프라이즈",
    "tools.database.plans.2.features.0": "무제한 접근",
    "tools.database.plans.2.features.1": "API (매일 10K 호출)",
    "tools.database.plans.2.features.2": "Webhook",
    "tools.database.plans.2.features.3": "사용자 정의 데이터",
    "tools.database.ctaDescription": "2,847개 TLD, 420M+ 도메인, 실시간 데이터를 손쉽게 접근하세요.",
    # ==================== MARKETPLACE MAIN ====================
    "mp.main.subtitle": "큐레이션된 인벤토리를 탐색하세요. 전체 통계 표시 — 이름 숨김. 공개하려면 지불하세요.",
    "mp.main.stats.0.label": "등록된 도메인",
    "mp.main.stats.1.label": "오늘 공개됨",
    "mp.main.stats.2.label": "평균 도메인 가치",
    "mp.main.stats.3.label": "총 판매액",
    "mp.main.filters.0": "모든 TLD",
    "mp.main.sortBy.0": "가치순 정렬",
    "mp.main.sortBy.1": "점수순 정렬",
    "mp.main.sortBy.2": "등록일순 정렬",
    "mp.main.dataLabels.0": "가치",
    "mp.main.dataLabels.1": "점수",
    "mp.main.dataLabels.2": "건강도",
    "mp.main.features.0.title": "이름 힌트 없음",
    "mp.main.features.0.desc": "이름을 제외한 모든 것을 표시합니다. 별표 없음, 부분 공개 없음. 인텔리전스만.",
    "mp.main.features.1.title": "공개하려면 지불",
    "mp.main.features.1.desc": "도메인 가치에 따라 공개 가격이 다릅니다 — 저가치 이름 $5부터 프리미엄 이름 $50까지.",
    "mp.main.features.2.title": "어디서든 등록",
    "mp.main.features.2.desc": "공개 후 Dynadot, Namecheap 또는 Porkbun으로 링크됩니다. 등록할 위치를 선택하세요.",
    "mp.main.modal.desc": "도메인 이름을 공개하고 구매하려면 가입하세요.",
    # ==================== MARKETPLACE SELL ====================
    "mp.sell.subtitle": "Ceche에서 프리미엄 도메인을 등록하여 전 세계 자격을 갖춘 구매자에게 도달하세요.",
    "mp.sell.step0.title": "도메인 제출",
    "mp.sell.step0.desc": "도메인 이름을 입력하세요. 자동 평가를 수행하고 TXT/CNAME 레코드로 소유권을 확인합니다.",
    "mp.sell.step0.cta": "계속",
    "mp.sell.step1.title": "가격 설정",
    "mp.sell.step1.desc": "AI가 도메인 지표를 기반으로 가격을 제안합니다. 수락하거나 직접 설정할 수 있습니다.",
    "mp.sell.step1.suggested": "제안 가격: $12,500",
    "mp.sell.step1.cta": "계속",
    "mp.sell.step2.title": "목록 게시",
    "mp.sell.step2.desc": "목록 세부 정보를 검토하고 게시하세요. 도메인이 24시간 이내에 온라인으로 전환됩니다.",
    "mp.sell.step2.cta": "목록 게시",
    "mp.sell.fees.listing.tiers.0.tier": "표준 (.com, .net, .org)",
    "mp.sell.fees.listing.tiers.1.tier": "프리미엄 (.io, .co, .ai)",
    "mp.sell.fees.listing.tiers.2.tier": "초프리미엄 (단어, 브랜더블)",
    "mp.sell.fees.commission.tiers.0.tier": "$5,000 미만 도메인",
    "mp.sell.fees.commission.tiers.0.minimum": "$50",
    "mp.sell.fees.commission.tiers.1.tier": "$5,000–$50,000 도메인",
    "mp.sell.fees.commission.tiers.1.minimum": "$200",
    "mp.sell.fees.commission.tiers.2.tier": "$50,000 이상 도메인",
    "mp.sell.fees.commission.tiers.2.minimum": "협상 가능",
    "mp.sell.eligibility.items.0": "도메인이 등록되어 있고 활성 상태여야 합니다",
    "mp.sell.eligibility.items.1": "TXT 또는 CNAME 레코드로 소유권을 확인해야 합니다",
    "mp.sell.eligibility.items.2": "활성 UDRP 또는 법적 분쟁이 없어야 합니다",
    "mp.sell.eligibility.items.3": "도메인이 스팸 블랙리스트에 등록되어 있지 않아야 합니다",
    "mp.sell.tools.items.0.title": "분석 대시보드",
    "mp.sell.tools.items.0.desc": "실시간으로 각 목록의 조회수, 제안 및 전환율을 추적합니다.",
    "mp.sell.tools.items.1.title": "대량 등록",
    "mp.sell.tools.items.1.desc": "CSV 업로드로 여러 도메인 목록을 한 번에 가져오고 관리합니다.",
    "mp.sell.tools.items.2.title": "자동 가격 책정",
    "mp.sell.tools.items.2.desc": "도메인 지표와 시장 트렌드를 기반으로 한 AI 기반 제안 가격.",
    "mp.sell.cta.desc": "5분 이내에 첫 번째 도메인을 등록하세요.",
    # ==================== MARKETPLACE LUCK ====================
    "mp.luck.subtitle": "TLD를 선택하고, 3개 상자를 돌려, 프리미엄 도메인을 공개하세요. 귀하에게만 독점적으로 잠깁니다.",
    "mp.luck.locked.title": "도메인 잠김",
    "mp.luck.locked.desc": "상자를 선택하면 도메인이 귀하에게만 독점적으로 잠깁니다. 플랫폼의 다른 사용자는 어떤 방법으로도 구매할 수 없습니다. 즉시 구매를 완료하라는 메시지가 표시됩니다.",
    "mp.luck.howItWorks.steps.0.title": "TLD 선택",
    "mp.luck.howItWorks.steps.0.desc": ".com, .net, .io, .co 또는 모든 TLD를 균일 가격으로 선택하세요.",
    "mp.luck.howItWorks.steps.1.title": "돌리고 선택",
    "mp.luck.howItWorks.steps.1.desc": "세 개의 닫힌 상자가 나타납니다. 애니메이션이 멈추면 하나를 선택하세요.",
    "mp.luck.howItWorks.steps.2.title": "공개 및 구매",
    "mp.luck.howItWorks.steps.2.desc": "도메인이 공개되고 잠깁니다. 즉시 등록하라는 메시지가 표시됩니다.",
    "mp.luck.cta.title": "탐색을 선호하시나요?",
    "mp.luck.cta.desc": "모든 목록에 대한 상세한 통계와 함께 전체 마켓플레이스를 탐색하세요.",
    "mp.luck.modal.desc": "이 도메인을 귀하에게만 독점적으로 잠그려면 가입하세요.",
    # ==================== MARKETPLACE CURATED ====================
    "mp.curated.subtitle": "상업적 의도와 SEO 권위별로 선별된 프리미엄 도메인. 각 목록에는 전체 인텔리전스 보고서와 밸류에이션이 포함됩니다.",
    "mp.curated.featured.label": "추천 도메인",
    "mp.curated.featured.hidden": "구매 전 이름 숨김",
    "mp.curated.featured.instant": "즉시 구매",
    "mp.curated.features.0": "도메인 전문가가 수동으로 선별",
    "mp.curated.features.1": "전체 인텔리전스 보고서 포함",
    "mp.curated.features.2": "소유권 확인 및 깨끗한 이력",
    "mp.curated.features.3": "안전한 결제로 즉시 구매",
    "mp.curated.features.4": "제안을 위한 협상 도구",
    "mp.curated.features.5": "등록 기관 지원으로 안내된 이전",
    "mp.curated.howItWorks.steps.0.title": "목록 탐색",
    "mp.curated.howItWorks.steps.0.desc": "각 �레이션 도메인에는 밸류에이션, SEO 지표 및 상업적 의도 점수가 포함됩니다.",
    "mp.curated.howItWorks.steps.1.title": "제안하기",
    "mp.curated.howItWorks.steps.1.desc": "바로 구매하거나 제안을 제출하세요. 시스템이 자동으로 상대 제안을 처리합니다.",
    "mp.curated.howItWorks.steps.2.title": "구매 완료",
    "mp.curated.howItWorks.steps.2.desc": "안전한 결제. 24시간 이내에 전면 지원으로 도메인이 이전됩니다.",
    "mp.curated.cta.title": "모든 큐레이션 도메인 탐색",
    "mp.curated.cta.desc": "매주 새로운 수동 선별 프리미엄 도메인으로 업데이트됩니다.",
    # ==================== MARKETPLACE UNMASKING ====================
    "mp.unmasking.subtitle": "블라인드 마켓플레이스는 도메인 이름을 프론트 러닝과 스나이핑으로부터 보호합니다. 다음은 프로세스입니다.",
    "mp.unmasking.steps.0.title": "탐색",
    "mp.unmasking.steps.0.desc": "블라인드 마켓플레이스를 탐색하세요. 전체 통계 표시 — 도메인 이름 숨김. TLD, 카테고리 또는 밸류에이션 범위별로 필터링.",
    "mp.unmasking.steps.1.title": "공개하려면 지불",
    "mp.unmasking.steps.1.desc": "마음에 드는 목록을 찾으면 공개 수수료를 지불하세요 (도메인 가치에 따라 $5–$50).",
    "mp.unmasking.steps.2.title": "공개 및 검사",
    "mp.unmasking.steps.2.desc": "도메인 이름이 공개됩니다. 검사하고 결정할 시간이 5분 있습니다. 다른 사람은 볼 수 없거나 구매할 수 없습니다.",
    "mp.unmasking.steps.3.title": "재검사 또는 포기",
    "mp.unmasking.steps.3.desc": "포기하면 도메인이 블라인드 풀로 돌아갑니다. 진행하면 귀하에게만 독점적으로 잠깁니다.",
    "mp.unmasking.steps.4.title": "완료 또는 포기",
    "mp.unmasking.steps.4.desc": "파트너 등록 기관(Dynadot, Namecheap, Porkbun)을 통해 도메인을 등록하거나 포기하세요. 의무 없음.",
    "mp.unmasking.vault.desc": "공개되지 않은 모든 도메인 이름은 암호화된 볼트에 저장됩니다. 부분 이름, 별표, 힌트 없음. 이름을 보는 유일한 방법은 공개 수수료를 지불하는 것입니다. 이를 통해 도메인 프론트 러닝을 제거하고 모든 사람에게 공정한 가격을 보장합니다.",
    "mp.unmasking.features.0.title": "암호화된 볼트",
    "mp.unmasking.features.0.desc": "제로 널리지 암호화로 저장된 도메인 이름.",
    "mp.unmasking.features.1.title": "5분 잠금",
    "mp.unmasking.features.1.desc": "공개 후 5분간의 독점 접근.",
    "mp.unmasking.features.2.title": "의무 없음",
    "mp.unmasking.features.2.desc": "언제든지 포기 가능. 커밋 불필요.",
    "mp.unmasking.cta.title": "탐색할 준비가 되셨나요?",
    "mp.unmasking.cta.desc": "전체 인텔리전스 데이터가 포함된 수천 개의 프리미엄 도메인을 탐색하세요.",
    # ==================== SOLUTIONS INDEX ====================
    "sol.index.subtitle": "투자하든, 구축하든, 중개하든 — Ceche에는 도메인 전략을 지원하는 도구, 데이터 및 마켓플레이스가 있습니다.",
    "sol.index.personas.0.title": "도메인 투자자",
    "sol.index.personas.0.desc": "포트폴리오 수익 분석, 플리퍼 메트릭 및 드롭 캡처 알림. 도메인 투자 수익을 극대화하세요.",
    "sol.index.personas.0.statLabel": "수수료 등급",
    "sol.index.personas.1.title": "스타트업 창업자",
    "sol.index.personas.1.desc": "브랜더빌리티 인덱스, 키워드 발음 가능성 및 확장 침투 도구. 스타트업에 완벽한 도메인을 찾으세요.",
    "sol.index.personas.1.statLabel": "스코어링 차원",
    "sol.index.personas.2.title": "SEO 대행사",
    "sol.index.personas.2.desc": "만료된 도메인 백링크 권위 스코어링 및 스팸 페널티 복구 감사. 대행사 성장을 위한 데이터 기반 도메인 인수.",
    "sol.index.personas.2.statLabel": "일일 API 호출",
    "sol.index.personas.3.title": "사용 가능한 도메인 찾기",
    "sol.index.personas.3.desc": "사용 가능한 도메인 이름을 위해 수백만 가지 조합을 스캔하세요. 스마트 제안과 실시간 사용 가능 확인.",
    "sol.index.personas.3.statLabel": "스캔된 TLD",
    "sol.index.personas.4.title": "연구 인텔리전스",
    "sol.index.personas.4.desc": "인수 전 심층 도메인 분석. 포괄적인 인텔리전스 보고서로 현명한 결정을 내리세요.",
    "sol.index.personas.4.statLabel": "구매 의도 점수",
    "sol.index.personas.5.title": "프리미엄 도메인 구매",
    "sol.index.personas.5.desc": "안전하고 투명한 거래를 통해 고가치 도메인을 확보하세요. 빠르고 안정적입니다.",
    "sol.index.personas.5.statLabel": "공개 수수료 범위",
    # ==================== SOLUTIONS INVESTORS ====================
    "sol.investors.desc": "포트폴리오 수익 분석, 플리퍼 밸류에이션 메트릭, 드롭 캡처 알림 및 8–15%의 수수료 등급. 시장을 능가하는 데 필요한 모든 것.",
    "sol.investors.cta.0": "투자 시작",
    "sol.investors.cta.1": "가격 보기",
    "sol.investors.stats.0.label": "스코어링 차원",
    "sol.investors.stats.1.label": "수수료 등급",
    "sol.investors.stats.2.label": "스캔된 TLD",
    "sol.investors.stats.3.label": "공개 수수료 범위",
    "sol.investors.problem.title": "투자자의 문제",
    "sol.investors.problem.desc": "전통적인 도메인 투자에는 여러 도구를 동시에 사용하고, 불투명한 수수료를 지불하고, 밸류에이션을 추측해야 합니다. 더 빠른 구매자에게 거래를 놓치고 수수료를 과다 지불합니다.",
    "sol.investors.problem.items.0": "TLD 전반에 걸친 통일된 스코어링 모델 부재",
    "sol.investors.problem.items.1": "숨겨진 수수료가 이익 마진을 잠식",
    "sol.investors.problem.items.2": "수동 드롭 캡처로 기회 상실",
    "sol.investors.problem.items.3": "수수료 구조가 플리핑 이익을 잠식",
    "sol.investors.solution.title": "Ceche 솔루션",
    "sol.investors.solution.desc": "16차원 스코어링, 최소 금액이 있는 등급 수수료, 실시간 알림, 그리고 캐주얼 구매자가 아닌 투자자를 위해 설계된 마켓플레이스를 갖춘 단일 플랫폼.",
    "sol.investors.solution.items.0": "모든 도메인에 대한 16차원 스코어링",
    "sol.investors.solution.items.1": "투명한 등급 수수료: 15%/12%/10%/8%",
    "sol.investors.solution.items.2": "만료 도메인 드롭 캡처 알림",
    "sol.investors.solution.items.3": "한 번에 최대 5,000개 도메인 대량 스캔",
    "sol.investors.commission.title": "등급 수수료 구조",
    "sol.investors.commission.headers.0": "등급",
    "sol.investors.commission.headers.1": "수수료",
    "sol.investors.commission.headers.2": "최소 금액",
    "sol.investors.commission.rows.0.tier": "스타터",
    "sol.investors.commission.rows.1.tier": "성장",
    "sol.investors.commission.rows.2.tier": "프로",
    "sol.investors.commission.rows.3.tier": "엔터프라이즈",
    "sol.investors.tools.0.title": "SEO 스캐너",
    "sol.investors.tools.0.desc": "초 단위로 백링크 프로필과 도메인 권위를 감사합니다.",
    "sol.investors.tools.1.title": "확장 인사이트",
    "sol.investors.tools.1.desc": "전체 16차원 심층 분석으로 기본을 넘어선 분석.",
    "sol.investors.tools.2.title": "대량 분석기",
    "sol.investors.tools.2.desc": "단일 배치 실행에서 최대 5,000개 도메인에 점수를 매깁니다.",
    "sol.investors.tools.3.title": "상표 모니터",
    "sol.investors.tools.3.desc": "포트폴리오의 상표 충돌에 대한 자동 알림.",
    "sol.investors.gettingStarted.steps.0.title": "계정 만들기",
    "sol.investors.gettingStarted.steps.0.desc": "30초 만에 무료 가입",
    "sol.investors.gettingStarted.steps.1.title": "플랜 선택",
    "sol.investors.gettingStarted.steps.1.desc": "무료, 스타트업 ($79/월) 또는 엔터프라이즈 ($129/월)",
    "sol.investors.gettingStarted.steps.2.title": "도메인 스캔",
    "sol.investors.gettingStarted.steps.2.desc": "SEO 스캐너 또는 대량 분석기 실행",
    "sol.investors.gettingStarted.steps.3.title": "점수 분석",
    "sol.investors.gettingStarted.steps.3.desc": "16차원 보고서 검토",
    "sol.investors.gettingStarted.steps.4.title": "인수 및 플리핑",
    "sol.investors.gettingStarted.steps.4.desc": "등급 수수료로 구매, 보유 또는 재판매",
    "sol.investors.ctaDesc": "Ceche를 사용하여 도메인 투자 수익을 극대화하는 수천 명의 투자자에 합류하세요.",
    # ==================== SOLUTIONS FOUNDERS ====================
    "sol.founders.desc": "AI 기반 브랜더빌리티 스코어링, 발음 가능성 분석 및 상표 스크리닝 — 이름을 커밋하기 전에 필요한 모든 것.",
    "sol.founders.steps.0.title": "브랜드 설명",
    "sol.founders.steps.0.desc": "스타트업, 업계 및 청중에 대한 간략한 설명을 입력하세요.",
    "sol.founders.steps.1.title": "점수 비교",
    "sol.founders.steps.1.desc": "4개 TLD 전반에 걸친 16차원 점수와 브랜더빌리티 등급을 받으세요.",
    "sol.founders.steps.2.title": "도메인 확보",
    "sol.founders.steps.2.desc": "등록하거나, 마켓플레이스에서 구매하거나, 만료 이름에 대한 알림을 설정하세요.",
    "sol.founders.features.0.title": "브랜더빌리티 인덱스",
    "sol.founders.features.0.desc": "브랜더빌리티, 기억 가능성 및 시장 잠재력을 평가하는 AI 기반 스코어링. 이름뿐만 아니라 브랜드 자산.",
    "sol.founders.features.1.title": "발음 가능성",
    "sol.founders.features.1.desc": "모음 균형, 자음 클러스터 및 바이그램 빈도 분석으로 도메인이 말하기, 철자하기 및 기억하기 쉬운지 확인합니다.",
    "sol.founders.features.2.title": "확장 침투",
    "sol.founders.features.2.desc": ".com, .io, .co 및 .ai의 시장 침투율을 비교하세요. 커밋하기 전에 어떤 TLD가 청중에게 적합한지 알아보세요.",
    "sol.founders.features.3.title": "소셜 가용성",
    "sol.founders.features.3.desc": "도메인 검색과 함께 주요 플랫폼에서 사용자 이름 가용성을 확인하세요. 한 번의 패스로 전체 브랜드 자산을 확보하세요.",
    "sol.founders.builtFor.0.title": "경쟁사 명명",
    "sol.founders.builtFor.0.desc": "경쟁 인사이트를 위해 업계의 명명 패턴을 분석하세요.",
    "sol.founders.builtFor.1.title": "상표 위험",
    "sol.founders.builtFor.1.desc": "브랜드 커밋 전 USPTO 및 WIPO 데이터베이스 스크리닝.",
    "sol.founders.builtFor.2.title": "평가 도구",
    "sol.founders.builtFor.2.desc": "신뢰 구간이 포함된 알고리즘 밸류에이션을 받으세요.",
    "sol.founders.builtFor.3.title": "SEO 스캐너",
    "sol.founders.builtFor.3.desc": "잠재 도메인의 백링크 프로필을 즉시 평가합니다.",
    "sol.founders.ctaDesc": "무료 계정으로 시작하세요. 4개 TLD에서 무제한 도메인에 점수를 매기세요.",
    # ==================== SOLUTIONS AGENCIES ====================
    "sol.agencies.desc": "만료된 도메인 백링크 권위 스코어링, 스팸 페널티 복구 감사 및 대행사 워크플로우를 위해 설계된 대량 도구. 프로젝트당 5,000개 이상의 도메인을 처리합니다.",
    "sol.agencies.stats.0.label": "대량 도메인",
    "sol.agencies.stats.1.label": "일일 API 호출",
    "sol.agencies.stats.2.label": "수수료 등급",
    "sol.agencies.stats.3.label": "공개 수수료",
    "sol.agencies.why.0.title": "고객 성과",
    "sol.agencies.why.0.desc": "데이터 기반 도메인 인수로 측정 가능한 투자 수익을 제공합니다. 고객에게 도메인이 왜 투자할 가치가 있는지 정확히 보여주세요.",
    "sol.agencies.why.1.title": "시간 절약",
    "sol.agencies.why.1.desc": "5,000개 도메인을 한 번에 대량 스캔하고 16차원으로 점수를 매깁니다. 며칠이 걸리던 일이 몇 분으로 단축됩니다.",
    "sol.agencies.why.2.title": "수익 성장",
    "sol.agencies.why.2.desc": "거래량이 증가함에 따라 수수료 등급이 낮아집니다. 8–15% 등급 수수료와 최소 기반 가격으로 거래당 더 많이 벌세요.",
    "sol.agencies.features.0.title": "만료된 도메인 권위",
    "sol.agencies.features.0.desc": "인수를 위해 만료된 도메인의 백링크 프로필을 평가합니다. dofollow/nofollow 비율, 앵커 텍스트 분포 및 링크 속도를 확인하세요.",
    "sol.agencies.features.1.title": "스팸 복구 감사",
    "sol.agencies.features.1.desc": "상세한 분석으로 Google 패널티를 식별하고 복구합니다. 도메인 건강을 복원하기 위한 실행 가능한 권장 사항을 받으세요.",
    "sol.agencies.features.2.title": "대량 분석기",
    "sol.agencies.features.2.desc": "배치당 최대 5,000개 도메인을 처리합니다. 고객 프레젠테이션용 점수, 지표 및 권장 사항이 포함된 CSV 보고서를 내보냅니다.",
    "sol.agencies.features.3.title": "보고 대시보드",
    "sol.agencies.features.3.desc": "고객 프레젠테이션용 화이트 레이블 보고서. 자동 보고서를 예약하고 여러 프로젝트의 인수 투자 수익을 추적합니다.",
    "sol.agencies.plans.0.name": "무료",
    "sol.agencies.plans.0.period": "/하루 3개 도메인",
    "sol.agencies.plans.0.features.0": "16차원 스코어링",
    "sol.agencies.plans.0.features.1": "SEO 스캐너",
    "sol.agencies.plans.0.features.2": "기본 인사이트",
    "sol.agencies.plans.0.cta": "시작하기",
    "sol.agencies.plans.1.name": "스타트업",
    "sol.agencies.plans.1.features.0": "하루 12개 도메인",
    "sol.agencies.plans.1.features.1": "확장 인사이트",
    "sol.agencies.plans.1.features.2": "상표 모니터",
    "sol.agencies.plans.1.features.3": "우선 지원",
    "sol.agencies.plans.1.cta": "체험 시작",
    "sol.agencies.plans.2.name": "엔터프라이즈",
    "sol.agencies.plans.2.features.0": "무제한 스코어링",
    "sol.agencies.plans.2.features.1": "대량 분석기 (5K)",
    "sol.agencies.plans.2.features.2": "API (매일 10K 호출)",
    "sol.agencies.plans.2.features.3": "화이트 레이블 보고서",
    "sol.agencies.plans.2.cta": "영업팀 문의",
    "sol.agencies.ctaDesc": "무료 계정으로 시작하거나 대량 가격에 대해 팀과 상담하세요.",
    # ==================== SOLUTIONS AVAILABLE ====================
    "sol.available.desc": "사용 가능한 도메인 이름을 위해 수백만 가지 조합을 스캔하세요. 스마트 제안, 실시간 사용 가능 확인 및 등록 기관 전반의 가격 비교.",
    "sol.available.discovery.desc1": "키워드, 업계 또는 브랜드 컨셉을 입력하면 Ceche가 수백 가지 사용 가능한 옵션을 생성합니다. 길이, TLD, 가격 범위 및 브랜더빌리티 점수별로 필터링하세요.",
    "sol.available.discovery.desc2": "모든 결과에는 16차원 점수가 포함되어 있어 진정한 시장 잠재력을 가진 도메인을 알 수 있습니다 — 사용 가능성뿐만 아니라.",
    "sol.available.filters.title": "필터 옵션",
    "sol.available.filters.items.0.label": "TLD",
    "sol.available.filters.items.1.label": "최대 길이",
    "sol.available.filters.items.1.value": "최대 15자",
    "sol.available.filters.items.2.label": "가격 범위",
    "sol.available.filters.items.2.value": "$8 – $500/년",
    "sol.available.filters.items.3.label": "브랜더빌리티",
    "sol.available.filters.items.3.value": "높음 / 중간 / 낮음",
    "sol.available.filters.items.4.label": "구매 의도",
    "sol.available.filters.items.4.value": "점수 0–100",
    "sol.available.filters.items.5.label": "사용 가능",
    "sol.available.filters.items.5.value": "즉시 확인",
    "sol.available.filters.items.6.label": "가격 비교",
    "sol.available.filters.items.6.value": "다중 등록 기관",
    "sol.available.timeline.steps.0.title": "기준 설정",
    "sol.available.timeline.steps.0.desc": "키워드, TLD, 가격 범위 및 브랜더빌리티 임계값을 정의하세요.",
    "sol.available.timeline.steps.1.title": "모니터링 및 알림",
    "sol.available.timeline.steps.1.desc": "Ceche는 매일 스캔하고 일치하는 도메인이 나타나면 알림을 보냅니다.",
    "sol.available.timeline.steps.2.title": "즉시 인수",
    "sol.available.timeline.steps.2.desc": "원클릭 등록 또는 안전한 결제로 마켓플레이스 구매.",
    "sol.available.plans.0.name": "무료",
    "sol.available.plans.0.features.0": "하루 3개 도메인",
    "sol.available.plans.0.features.1": "기본 스코어링",
    "sol.available.plans.0.features.2": "1개 TLD",
    "sol.available.plans.1.name": "스타트업",
    "sol.available.plans.1.features.0": "하루 12개 도메인",
    "sol.available.plans.1.features.1": "확장 인사이트",
    "sol.available.plans.1.features.2": "4개 TLD",
    "sol.available.plans.2.name": "엔터프라이즈",
    "sol.available.plans.2.features.0": "무제한 스코어링",
    "sol.available.plans.2.features.1": "대량 분석기",
    "sol.available.plans.2.features.2": "API 접근",
    "sol.available.bulk.title": "대량 도메인 스캐너",
    "sol.available.bulk.desc": "최대 5,000개 도메인의 CSV를 업로드하고 몇 분 만에 스코어링된 결과를 받으세요. 포트폴리오 감사 및 대규모 탐색에 적합합니다.",
    "sol.available.bulk.note": "엔터프라이즈 플랜 ($129/월)에서 사용 가능. 매일 10,000번의 API 호출이 포함됩니다.",
    "sol.available.ctaDesc": "하루 3번의 무료 도메인 검색으로 시작하세요.",
    # ==================== SOLUTIONS RESEARCH ====================
    "sol.research.desc": "포괄적인 인텔리전스 보고서로 현명한 결정을 내리세요. 16차원 스코어링, 소유권 역사, 백링크 프로필 및 위험 평가 — 모두 하나의 문서에.",
    "sol.research.breadcrumb.0": "솔루션",
    "sol.research.breadcrumb.1": "연구 인텔리전스",
    "sol.research.sections.0.title": "16차원 스코어링",
    "sol.research.sections.0.desc": "모든 도메인은 브랜더빌리티, SEO 강점, 시장 수요 및 위험 요소를 포함한 16개의 개별 차원에서 평가됩니다. 종합 구매 의도 점수 (0–100)는 도메인을 비교할 수 있는 단일 숫자를 제공합니다.",
    "sol.research.sections.1.title": "소유권 역사",
    "sol.research.sections.1.desc": "전체 WHOIS 역사 및 소유권 전환. 도메인이 몇 번이나 손바뀌었는지, 이전 사용 사례 및 관련 평판 문제를 확인하세요.",
    "sol.research.sections.2.title": "백링크 프로필",
    "sol.research.sections.2.desc": "품질 스코어링이 포함된 상세한 백링크 분석. dofollow/nofollow 비율, 앵커 텍스트 분포, 인용 도메인 및 시간에 따른 링크 속도 추세.",
    "sol.research.sections.3.title": "트래픽 추정",
    "sol.research.sections.3.desc": "SEO 지표, 키워드 순위 및 과거 데이터 기반의 월간 트래픽 예측. 투자 전에 유기적 잠재력을 이해하세요.",
    "sol.research.sections.4.title": "밸류에이션 범위",
    "sol.research.sections.4.desc": "신뢰 구간이 있는 알고리즘 가격. .com, .io, .co 및 .ai에서 최근 유사 판매와 비교하여 공정 시장 가치를 이해하세요.",
    "sol.research.sections.5.title": "위험 평가",
    "sol.research.sections.5.desc": "상표 충돌, 스팸 역사, Google 패널티 상태 및 등록 위험 분석. 자본을 투입하기 전에 전체 그림을 파악하세요.",
    "sol.research.compareHeaders.0": "기능",
    "sol.research.compareRows.0.feature": "16차원 스코어링",
    "sol.research.compareRows.0.dynadot": "✗",
    "sol.research.compareRows.0.godaddy": "✗",
    "sol.research.compareRows.1.feature": "구매 의도 점수",
    "sol.research.compareRows.1.dynadot": "✗",
    "sol.research.compareRows.1.godaddy": "✗",
    "sol.research.compareRows.2.feature": "대량 분석 (5K+)",
    "sol.research.compareRows.2.ceche": "✓",
    "sol.research.compareRows.2.dynadot": "제한적",
    "sol.research.compareRows.2.godaddy": "✗",
    "sol.research.compareRows.3.feature": "API 접근",
    "sol.research.compareRows.3.ceche": "매일 10K",
    "sol.research.compareRows.3.dynadot": "기본",
    "sol.research.compareRows.3.godaddy": "유료 추가",
    "sol.research.compareRows.4.feature": "상표 모니터",
    "sol.research.compareRows.4.ceche": "✓",
    "sol.research.compareRows.4.dynadot": "✗",
    "sol.research.compareRows.4.godaddy": "유료",
    "sol.research.compareRows.5.feature": "등급 수수료",
    "sol.research.compareRows.5.ceche": "8–15%",
    "sol.research.compareRows.5.dynadot": "고정",
    "sol.research.compareRows.5.godaddy": "고정 20%+",
    "sol.research.compareRows.6.feature": "분석된 TLD",
    "sol.research.compareRows.6.ceche": "4",
    "sol.research.compareRows.6.dynadot": "10+",
    "sol.research.compareRows.6.godaddy": "10+",
    "sol.research.ctaDesc": "모든 도메인에 대한 심층 인텔리전스를 얻으세요. 무료 계정으로 시작하세요.",
    # ==================== SOLUTIONS PREMIUM ====================
    "sol.premium.heroDesc": "안전한 결제, 투명한 가격 및 72시간 검사 기간. 프리미엄 도메인을 올바르게 구매하세요 — 안전하고 공정하게.",
    "sol.premium.steps.0.title": "발견 및 평가",
    "sol.premium.steps.0.desc": "전체 16차원 인텔리전스 보고서가 포함된 큐레이션된 프리미엄 도메인을 탐색하세요. 제안 전에 소유권 역사, 백링크 프로필 및 공정 시장 밸류에이션을 확인하세요.",
    "sol.premium.steps.1.title": "협상 및 거래",
    "sol.premium.steps.1.desc": "제안, 상대 제안을 하고 안전하게 거래를 성사시키세요. 도메인 이전이 확인되고 검증될 때까지 결제가 안전하게 처리됩니다.",
    "sol.premium.steps.2.title": "검사 및 확인",
    "sol.premium.steps.2.desc": "이전 후 72시간 검사 기간. 판매자가 결제를 받기 전에 도메인이 모든 기대를 충족하는지 확인하세요. 불만족 시 전액 환불.",
    "sol.premium.trust.0.title": "안전한 결제",
    "sol.premium.trust.0.desc": "도메인 이전이 양 당사자에 의해 확인되고 검증될 때까지 결제가 안전하게 처리됩니다.",
    "sol.premium.trust.1.title": "72시간 검사",
    "sol.premium.trust.1.desc": "이전 후 완전한 검사 기간. 도메인을 테스트하고, 레코드를 검증하며, 요구 사항을 충족하는지 확인하세요.",
    "sol.premium.trust.2.title": "다중 결제 옵션",
    "sol.premium.trust.2.desc": "신용 카드, 송금 및 암호화폐를 받습니다. 숨겨진 비용이나 환전 놀라움 없음.",
    "sol.premium.pricingHeaders.0": "수수료 유형",
    "sol.premium.pricingHeaders.1": "금액",
    "sol.premium.pricingHeaders.2": "참고",
    "sol.premium.pricingRows.0.type": "공개 수수료 (표준)",
    "sol.premium.pricingRows.0.notes": "도메인 공개당 일회성",
    "sol.premium.pricingRows.1.type": "공개 수수료 (우선)",
    "sol.premium.pricingRows.1.notes": "전체 보고서가 포함된 가속 공개",
    "sol.premium.pricingRows.2.type": "구매자 수수료",
    "sol.premium.pricingRows.2.notes": "Ceche에서 구매자는 수수료 0%",
    "sol.premium.pricingRows.3.type": "거래 수수료",
    "sol.premium.pricingRows.3.notes": "안전한 결제에 추가 요금 없음",
    "sol.premium.ctaDesc": "모든 구매에 안전하고 투명한 거래와 안전한 결제가 포함됩니다.",
    # ==================== RESOURCES BLOG ====================
    "res.blog.subtitle": "데이터가 아닌 직관으로 거래하는 도메인 투자자를 위한 전략 가이드, 시장 분석 및 프레임워크.",
    "res.blog.categories.0": "전략",
    "res.blog.categories.1": "시장 데이터",
    "res.blog.categories.2": "튜토리얼",
    "res.blog.categories.3": "업계 뉴스",
    "res.blog.categories.4": "사례 연구",
    "res.blog.marquee": "도메인 밸류에이션 · 시장 보고서 · 포트폴리오 분석 · 블라인드 마켓플레이스 · 16차원 프레임워크 · 건강 점수 · CPC 데이터 · 브랜더빌리티 인덱스 · 행운 시도 ·",
    "res.blog.articles.0.title": "왜 프리미엄 .com 도메인이 새로운 gTLD를 계속 압도하는가",
    "res.blog.articles.1.title": "포트폴리오 건강 점수의 숨겨진 투자 수익",
    "res.blog.articles.2.title": "간과하는 도메인 평가의 5가지 위험 신호",
    "res.blog.articles.3.title": "추측 없이 도메인 가격을 매기는 방법",
    "res.blog.articles.4.title": "블라인드 경매 vs. 고정 목록: 데이터 비교",
    "res.blog.articles.5.title": "처음부터 도메인 리셀링 워크플로우 구축",
    "res.blog.cta.title": "전체 라이브러리를 원하시나요?",
    "res.blog.cta.desc": "전자책을 다운로드하여 도메인 투자에 대해 더 깊이 파고드세요.",
    # ==================== RESOURCES EBOOKS ====================
    "res.ebooks.subtitle": "모든 수준의 도메인 투자자를 위한 무료 가이드, 프레임워크 및 플레이북.",
    "res.ebooks.featured.badge": "추천",
    "res.ebooks.featured.title": "도메인 투자자 플레이북",
    "res.ebooks.featured.desc": "도메인 이름을 구매, 평가 및 판매하여 수익을 올리는 결정적인 가이드. 상위 리셀러가 사용하는 42페이지의 실행 가능한 프레임워크, 사례 연구 및 Ceche 전략.",
    "res.ebooks.featured.stats.0.label": "다운로드",
    "res.ebooks.featured.stats.1.label": "페이지",
    "res.ebooks.featured.stats.2.label": "평점",
    "res.ebooks.featured.cta": "무료 사본 받기 →",
    "res.ebooks.catalogTitle": "Ceche의 더 많은 자료",
    "res.ebooks.catalog.0.title": "도메인 평가사 툴킷",
    "res.ebooks.catalog.0.desc": "추측이 아닌 데이터를 사용하여 도메인에 가치를 매기는 단계별 가이드. 16차원 프레임워크, 건강 스코어링 및 비교 시장 분석을 다룹니다.",
    "res.ebooks.catalog.1.title": "블라인드 마켓플레이스 플레이북",
    "res.ebooks.catalog.1.desc": "Ceche의 블라인드 입찰 시스템이 가격 인플레이션을 어떻게 제거하고 구매자에게 이점을 제공하는지. 협상 템플릿과 입찰 전략 프레임워크가 포함됩니다.",
    "res.ebooks.catalog.2.title": "포트폴리오 건강 감사 가이드",
    "res.ebooks.catalog.2.desc": "도메인 포트폴리오에 대한 전체 건강 검진을 수행하세요. Ceche의 스코어링 시스템으로 저조자, 갱신 함정 및 숨겨진 보물을 식별합니다.",
    "res.ebooks.catalog.3.title": "도메인 리셀링 101",
    "res.ebooks.catalog.3.desc": "인수부터 마감까지 — 새로운 도메인 리셀러가 필요한 모든 것. 실제 데이터로 뒷받침되는 가격 전략, 구매자 아웃리치 및 마감 기법.",
    "res.ebooks.cta.title": "더 많은 기사와 시장 인사이트를 원하시나요?",
    "res.ebooks.cta.desc": "블로그는 도메인 전략, 가격 모델 및 업계 분석을 다룹니다.",
    "res.ebooks.modal.title": "다운로드하려면 계정을 만드세요",
    "res.ebooks.modal.desc": "모든 Ceche 전자책과 가이드는 등록 사용자에게 무료입니다.",
    "res.ebooks.modal.cta": "무료 계정 만들기",
    "res.ebooks.modal.back": "돌아가기",
    # ==================== RESOURCES CASES ====================
    "res.cases.desc": "도메인 투자자, 스타트업 및 포트폴리오 관리자가 Ceche를 사용하여 더 빠르고 현명한 결정을 내리는 방법을 알아보세요. 모든 사례 연구는 실제 데이터로 뒷받침됩니다 — 선별된 성공 사례가 아닙니다.",
    "res.cases.stats.0.label": "활성 사용자",
    "res.cases.stats.1.label": "정확도",
    "res.cases.comingSoon.title": "사례 연구 곧 출시",
    "res.cases.comingSoon.desc": "투자자들이 Ceche 도구를 사용하여 저평가된 도메인을 발견하고, 더 스마트하게 협상하며, 거래를 더 빠르게 성사시키는 방법을 문서화하고 있습니다. 곧 심층 분석을 확인하세요.",
    "res.cases.comingSoon.appraisal": "평가 도구 시도 →",
    "res.cases.comingSoon.marketplace": "마켓플레이스 탐색",
    "res.cases.comingSoon.pricing": "가격 보기",
    "res.cases.cta.title": "공유할 이야기가 있으신가요?",
    "res.cases.cta.desc": "Ceche와의 경험을 소개하고 싶습니다.",
    # ==================== COMPANY ABOUT ====================
    "company.about.desc": "프리미엄 이름이 매매되는 도메인 마켓플레이스 — 진정한 인텔리전스가 아닌 추측으로 작동합니다.",
    "company.about.cta.title": "다음 도메인을 찾을 준비가 되셨나요?",
    "company.about.cta.desc": "모든 이름은 데이터로 뒷받침됩니다. 마켓플레이스는 열려 있습니다.",
    "company.about.origin.p1": "도메인 중고 시장은 매년 30억 달러 이상의 거래를 생성하지만, 대부분의 마켓플레이스는 불투명하고, 스크래퍼에 의해 가격이 올라가며, 데이터가 아닌 추측에 기반하여 구축됩니다. Ceche는 이를 해결하기 위해 만들어졌습니다.",
    "company.about.origin.p2": "연구 플랫폼의 인텔리전스와 마켓플레이스의 거래 메커니즘을 결합했습니다. 먼저 숫자를 평가합니다 — 추정 가치, 건강 점수, CPC, 브랜더빌리티 — 이름은 공개 비용을 지불할 때만 나타납니다. 모든 밸류에이션은 공개된 방법론과 검증 가능한 데이터 세트로 뒷받침됩니다.",
    "company.about.founder.bio": "100개 이상의 도메인을 관리하는 도메인 이름 투자자 및 리셀러. 도메인 업계를 위한 지능형 인프라를 구축하는 에이전트 및 시스템 엔지니어. 나이지리아 아와 거주.",
    "company.about.values.items.0.desc": "방법론, 데이터 소스 및 정확도 지표를 공개합니다. 작동 방식을 이해하는 사용자는 우리의 말을 믿도록 요구하는 사용자보다 더 신뢰합니다.",
    "company.about.values.items.1.desc": "우리가 하는 모든 주장은 데이터로 뒷받침됩니다. 모든 도구는 측정 가능한 출력을 생성합니다. 데이터가 사용 가능할 때 추측에 의존하지 않습니다.",
    "company.about.values.items.2.desc": "빠르게 출시하고 반복합니다. 완벽은 진보의 적입니다 — 출시할 만큼 충분히 좋게 만든 다음 개선합니다.",
    # ==================== COMPANY AFFILIATES ====================
    "sol.investors.desc": "포트폴리오 수익 분석, 플리퍼 밸류에이션 메트릭, 드롭 캡처 알림 및 8–15%의 수수료 등급. 시장을 능가하는 데 필요한 모든 것.",
    "company.affiliates.desc": "파트너 프로그램에 가입하여 네트워크와 Ceche를 공유하고 추천하는 각 고객으로부터 반복 수수료를 받으세요.",
    "company.affiliates.benefits.0.title": "30% 반복 수수료",
    "company.affiliates.benefits.0.desc": "추천하는 모든 유료 고객으로부터 벌금 — 구독하는 동안. 상한선 없음, 제한 없음.",
    "company.affiliates.benefits.1.title": "90일 쿠키 윈도우",
    "company.affiliates.benefits.1.desc": "추천 링크가 방문자를 90일간 추적합니다. 몇 주 후에 돌아오더라도 크레딧을 받습니다.",
    "company.affiliates.benefits.2.title": "실시간 대시보드",
    "company.affiliates.benefits.2.desc": "클릭, 가입 및 수익을 실시간으로 추적합니다. 추측 없음, 월간 보고서를 기다릴 필요 없음.",
    "company.affiliates.benefits.3.title": "전용 파트너 지원",
    "company.affiliates.benefits.3.desc": "파트너 팀에 대한 우선 접근. 사용자 정의 랜딩 페이지, 프로모션 자산 및 캠페인 안내.",
    "company.affiliates.benefits.4.title": "즉시 지불",
    "company.affiliates.benefits.4.desc": "은행 송금 또는 PayPal로 매월 지불. 최소 임계값 없음. 지연 없음.",
    "company.affiliates.benefits.5.title": "무료 Premium 접근",
    "company.affiliates.benefits.5.desc": "활성 파트너는 무료 Ceche Pro 계정을 받습니다. 제품을 사용하고, 제품을 판매하고, 제품을 믿으세요.",
    "company.affiliates.cta.desc": "파트너 프로그램에 가입하고 몇 분 만에 추천을 시작하세요.",
    # ==================== HELP OVERVIEW ====================
    "helpOverview.sections.0.desc": "도메인 조회부터 대량 분석까지 모든 Ceche 도구에 대한 포괄적인 가이드.",
    "helpOverview.sections.1.desc": "대규모 프로그래밍 방식 도메인 인텔리전스를 위한 RESTful API 엔드포인트.",
    "helpOverview.sections.2.desc": "가격, 도구, 계정 등에 대한 일반적인 질문에 대한 답변.",
    "helpOverview.sections.3.desc": "도움말, 피드백 또는 파트너십 문의를 위해 지원팀에 연락하세요.",
    "helpOverview.sections.4.desc": "제품 업데이트, 새로운 기능 및 플랫폼 개선.",
    # ==================== HELP DOCS ====================
    "helpDocs.desc": "Ceche 도움말 센터는 SEO 스캐너, 확장 인사이트, 대량 분석기, 상표 모니터, 도메인 데이터베이스 및 API를 다룹니다. 도구, 주제 및 난이도별로 구성된 320개 이상의 기사.",
    "helpDocs.tools.0.name": "도메인 조회",
    "helpDocs.tools.0.desc": "무료 도구. 모든 도메인의 WHOIS 데이터, DNS 레코드 및 등록 기관 정보.",
    "helpDocs.tools.0.pricing": "무료",
    "helpDocs.tools.0.features.0": "WHOIS 조회",
    "helpDocs.tools.0.features.1": "DNS 레코드 내보내기 (A, AAAA, MX, TXT, CNAME)",
    "helpDocs.tools.0.features.2": "등록 기관 감지",
    "helpDocs.tools.0.features.3": "만료 추적",
    "helpDocs.tools.1.name": "16차원 평가",
    "helpDocs.tools.1.desc": "16개 분석 차원을 사용한 심층 도메인 밸류에이션 — RDAP, TLD 스코어링, 브랜더빌리티, 상업적 의도 등.",
    "helpDocs.tools.1.pricing": "무료 (하루 3번 미서명 / 12번 서명)",
    "helpDocs.tools.1.features.0": "16개 스코어링 차원",
    "helpDocs.tools.1.features.1": "시장 기반 가격",
    "helpDocs.tools.1.features.2": "비교 분석",
    "helpDocs.tools.1.features.3": "신뢰 구간",
    "helpDocs.tools.2.name": "SEO 스캐너",
    "helpDocs.tools.2.desc": "3-5초 만에 검색 가시성, 백링크 품질, 유기적 트래픽 및 SEO 권위를 평가합니다.",
    "helpDocs.tools.2.pricing": "프리미엄",
    "helpDocs.tools.2.features.0": "도메인 등급 0-100",
    "helpDocs.tools.2.features.1": "유기적 트래픽 추정",
    "helpDocs.tools.2.features.2": "키워드 순위",
    "helpDocs.tools.2.features.3": "SEO 점수 종합",
    "helpDocs.tools.3.name": "확장 인사이트",
    "helpDocs.tools.3.desc": "심층 실사 — 16차원 밸류에이션, 상표 스크리닝, 유사 판매 및 구매 의도 스코어링.",
    "helpDocs.tools.3.pricing": "$5-$50/보고서",
    "helpDocs.tools.3.features.0": "6개 보고서 섹션",
    "helpDocs.tools.3.features.1": "상표 충돌 확인",
    "helpDocs.tools.3.features.2": "구매 의도 점수 0-100",
    "helpDocs.tools.3.features.3": "PDF/JSON 내보내기",
    "helpDocs.tools.4.name": "대량 도메인 감사",
    "helpDocs.tools.4.desc": "최대 5,000개 도메인의 CSV를 업로드하세요. 밸류에이션, SEO 점수, 우선순위 순위 및 권장 조치를 받으세요.",
    "helpDocs.tools.4.pricing": "프리미엄 ($79+/월)",
    "helpDocs.tools.4.features.0": "배치당 5,000개 도메인",
    "helpDocs.tools.4.features.1": "우선순위 점수 1-100",
    "helpDocs.tools.4.features.2": "사용자 정의 스코어링 프로필",
    "helpDocs.tools.4.features.3": "CSV 내보내기",
    "helpDocs.tools.5.name": "상표 모니터",
    "helpDocs.tools.5.desc": "자동화된 USPTO 및 WIPO 스크리닝. 상표 충돌이 법적 문제가 되기 전에 알림을 받으세요.",
    "helpDocs.tools.5.pricing": "프리미엄 ($79+/월)",
    "helpDocs.tools.5.features.0": "매일 USPTO/WIPO 스캔",
    "helpDocs.tools.5.features.1": "4개 심각도 수준",
    "helpDocs.tools.5.features.2": "이메일 + SMS 알림",
    "helpDocs.tools.5.features.3": "목록당 5,000개 도메인",
    "helpDocs.tools.6.name": "도메인 데이터베이스",
    "helpDocs.tools.6.desc": "2,847개 TLD의 등록 통계, 가격 역사 및 갱신 비용. ICANN 영역 파일에서 매일 업데이트.",
    "helpDocs.tools.6.pricing": "무료 (현재 가격)",
    "helpDocs.tools.6.features.0": "2,847개 TLD 추적",
    "helpDocs.tools.6.features.1": "24개월 가격 역사",
    "helpDocs.tools.6.features.2": "420개 이상의 등록 기관 피드",
    "helpDocs.tools.6.features.3": "TLD, 키워드 또는 가격으로 검색",
    "helpDocs.tiers.0.tier": "무료",
    "helpDocs.tiers.0.features": "하루 12번의 평가, 기본 SEO 스캐너, 도움말 센터 접근",
    "helpDocs.tiers.1.tier": "스타트업",
    "helpDocs.tiers.1.features": "하루 30번의 평가, 전체 스캐너, 확장 인사이트, 대량 분석기, 상표 모니터",
    "helpDocs.tiers.2.tier": "엔터프라이즈",
    "helpDocs.tiers.2.features": "무제한 평가, 모든 스타트업 기능, API (매일 10K 호출), 전용 지원",
    # ==================== HELP FAQ ====================
    "helpFaq.desc": "Ceche에 대한 가장 일반적인 질문에 대한 답변 — 가격, 도구, API, 마켓플레이스 및 계정 관리.",
    "helpFaq.sections.0.items.0.q": "Ceche란 무엇인가요?",
    "helpFaq.sections.0.items.0.a": "Ceche는 프리미엄 이름이 매매되는 도메인 마켓플레이스입니다. 평가 엔진은 16차원 스코어링으로 가치를 증명합니다. 검색 및 스캐너 도구는 이름을 찾는 데 도움이 됩니다. 모든 것이 마켓플레이스와 연결됩니다.",
    "helpFaq.sections.0.items.1.q": "평가 엔진은 어떻게 작동하나요?",
    "helpFaq.sections.0.items.1.a": "평가 엔진은 Ceche의 독점 16차원 프레임워크를 사용하여 네 가지 카테고리에서 도메인을 평가합니다: 어휘 분석 (30%), 기술 권위 (25%), 시장 역학 (25%) 및 브랜더빌리티 (20%). 각 차원은 독립적으로 점수화되고 통계적으로 도출된 가중치를 사용하여 결합됩니다.",
    "helpFaq.sections.0.items.2.q": "Ceche는 어떤 TLD를 지원하나요?",
    "helpFaq.sections.0.items.2.a": "Ceche는 .com, .net, .io 및 .co 도메인을 지원합니다. 도메인 데이터베이스는 2,847개 TLD의 가격과 등록 데이터를 추적하지만, 평가 및 마켓플레이스 기능은 현재 이 네 가지 확장자로 제한됩니다.",
    "helpFaq.sections.0.items.3.q": "계정은 어떻게 만드나요?",
    "helpFaq.sections.0.items.3.a": "탐색 창의 '무료 가입'을 클릭하세요. 무료 계정에는 하루 12번의 평가, 기본 SEO 스캐너 접근 및 전체 도움말 센터 접근이 포함됩니다. 신용 카드 불필요.",
    "helpFaq.sections.1.items.0.q": "구독 등급은 무엇인가요?",
    "helpFaq.sections.1.items.0.a": "무료: 하루 12번의 평가, 기본 SEO 스캐너, 도움말 센터. 스타트업 ($79/월): 하루 30번의 평가, 전체 SEO 스캐너, 확장 인사이트 ($5-$50/보고서), 대량 분석기, 상표 모니터, 도메인 데이터베이스, 우선 지원. 엔터프라이즈 ($129/월): 무제한 평가, 모든 스타트업 기능, API 접근 (매일 10,000번의 호출), 전용 계정 관리자, 비공개 Slack 채널, 사용자 정의 보고.",
    "helpFaq.sections.1.items.1.q": "행운 시도 가격은 어떻게 작동하나요?",
    "helpFaq.sections.1.items.1.a": "행운 시도는 균일 가격으로 미스터리 도메인 인수를 제공합니다: .com ($79), .net ($39), .io ($29), .co ($9) 또는 모든 TLD ($19 균일). 각 인수에는 16차원 스코어링이 포함된 Ceche 밸류에이션 보고서가 포함됩니다.",
    "helpFaq.sections.1.items.2.q": "마켓플레이스 수수료는 얼마인가요?",
    "helpFaq.sections.1.items.2.a": "표준 등록: 도메인당 $5. 우선 등록: 도메인당 $10 (72시간 가시성 향상 포함). 수수료: 슬라이딩 스케일에 따라 최종 판매 가격의 8-15% — $500 미만 거래 15%, $500-$5,000 12%, $5,000-$50,000 10%, $50,000 이상 8%.",
    "helpFaq.sections.1.items.3.q": "환불을 제공하나요?",
    "helpFaq.sections.1.items.3.a": "아니요. 디지털 상품(공개, 구독, 마켓플레이스, 행운 시도)에 대한 모든 수수료는 환불 불가능합니다.",
    "helpFaq.sections.2.items.0.q": "SEO 스캐너와 확장 인사이트의 차이점은 무엇인가요?",
    "helpFaq.sections.2.items.0.a": "SEO 스캐너는 검색 가시성, 백링크 프로필, 유기적 트래픽 역사 및 키워드 관련성을 평가합니다 — 3-5초 만에 결과를 반환합니다. 확장 인사이트는 상표 스크리닝, 유사 판매 및 구매 의도 스코어링을 포함한 더 깊은 실사를 제공합니다.",
    "helpFaq.sections.2.items.1.q": "대량 분석기는 어떻게 작동하나요?",
    "helpFaq.sections.2.items.1.a": "하나의 열 (헤더: 'domain')과 행당 하나의 도메인이 포함된 CSV를 업로드하세요. 출력에는 도메인 이름, Ceche 밸류에이션, 16차원 점수, 우선순위 점수 (1-100), 권장 조치 및 추정 판매 시간이 포함됩니다. 5,000개 도메인의 처리 시간은 약 2분 28초입니다.",
    "helpFaq.sections.2.items.2.q": "상표 모니터는 어떻게 작동하나요?",
    "helpFaq.sections.2.items.2.a": "대시보드에서 모니터링 목록에 도메인을 추가하세요. 이 도구는 매일 새로운 USPTO 및 WIPO 제출물을 스크리닝합니다. 24시간 이내에 이메일 알림을 받습니다. 심각도 수준: 심각 (관련 클래스의 동일 마크), 높음 (다른 클래스의 유사 마크), 중간 (유사 마크, 다른 상품), 낮음 (부분 일치).",
    "helpFaq.sections.3.items.0.q": "API 요청은 어떻게 인증하나요?",
    "helpFaq.sections.3.items.0.a": "Authorization 헤더에 Bearer 토큰으로 API 키를 포함하세요: Authorization: Bearer YOUR_API_KEY. 계정 설정 > API 키에서 키를 생성하세요.",
    "helpFaq.sections.3.items.1.q": "API 속도 제한은 얼마인가요?",
    "helpFaq.sections.3.items.1.a": "무료: 매일 100번의 호출. 스타트업 ($79/월): 매일 500번의 호출. 엔터프라이즈 ($129/월): 매일 10,000번의 호출. 속도 제한은 매일 00:00 UTC에 리셋됩니다.",
    "helpFaq.sections.3.items.2.q": "어떤 SDK를 사용할 수 있나요?",
    "helpFaq.sections.3.items.2.a": "Python, JavaScript/Node.js, Go 및 Ruby용 공식 SDK를 사용할 수 있습니다. Webhook 구성은 지수 백오프 재시도 로직을 사용하여 자동 알림에 사용할 수 있습니다.",
    "helpFaq.sections.4.items.0.q": "지원팀에 어떻게 연락하나요?",
    "helpFaq.sections.4.items.0.a": "Premium 구독자는 4영업시간 이내에 응답을 받습니다. 무료 계정 사용자는 24영업시간 이내. 엔터프라이즈 구독자는 비공개 Slack 채널을 통해 지원팀에 연락할 수도 있습니다.",
    "helpFaq.sections.4.items.1.q": "구독을 취소할 수 있나요?",
    "helpFaq.sections.4.items.1.a": "네. 계정 설정 > 청구에서 언제든지 취소할 수 있습니다. 현재 청구 기간이 끝날 때까지 Premium 접근 권한을 유지합니다. 구독료는 환불 불가능합니다.",
    # ==================== HELP API ====================
    "helpApi.desc": "도메인 평가, 브랜더빌리티 스코어링, 상표 모니터링 및 마켓플레이스 목록 관리를 위한 통합 REST API. 모든 요청에는 Bearer 토큰이 필요합니다.",
    "helpApi.limits.0.tier": "무료",
    "helpApi.limits.0.limit": "매일 100번의 호출",
    "helpApi.limits.1.tier": "스타트업",
    "helpApi.limits.1.limit": "매일 500번의 호출",
    "helpApi.limits.2.tier": "엔터프라이즈",
    "helpApi.limits.2.limit": "매일 10,000번의 호출",
    # ==================== HELP CONTACT ====================
    "helpContact.desc": "Premium 구독자는 4영업시간 이내에 응답을 받습니다. 무료 계정 사용자는 24영업시간 이내.",
    "helpContact.form.subjects.0": "일반 문의",
    "helpContact.form.subjects.1": "기술 지원",
    "helpContact.form.subjects.2": "청구 문제",
    "helpContact.form.subjects.3": "파트너십",
    "helpContact.form.subjects.4": "언론 / 미디어",
    "helpContact.form.messagePlaceholder": "어떻게 도와드릴까요?",
    "helpContact.channels.email.title": "이메일",
    "helpContact.channels.slack.title": "엔터프라이즈 Slack",
    "helpContact.channels.slack.value": "엔터프라이즈 구독자를 위한 비공개 채널",
    "helpContact.responseTimes.times.0.tier": "엔터프라이즈",
    "helpContact.responseTimes.times.0.time": "4시간",
    "helpContact.responseTimes.times.1.tier": "스타트업",
    "helpContact.responseTimes.times.1.time": "4시간",
    "helpContact.responseTimes.times.2.tier": "무료",
    "helpContact.responseTimes.times.2.time": "24시간",
    "helpContact.businessHours.desc": "월-금, 오전 9:00 - 오후 6:00 ET. Premium 엔터프라이즈: 24/7 Slack 지원. 엔터프라이즈 구독자를 위한 주요 문제는 연중무휴 모니터링됩니다.",
    # ==================== LIMIT ====================
    "limit.desc": "이 요청이 통과되지 않았습니다. 오늘 무료 평가를 모두 사용했습니다. 속도 제한을 높이고 더 많은 도메인을 평가하려면 가입하세요.",
    "limit.currentLimits": "현재 제한",
    "limit.limits.0.tier": "미가입",
    "limit.limits.0.value": "하루 3번",
    "limit.limits.1.tier": "가입 (무료)",
    "limit.limits.1.value": "하루 12번",
    "limit.limits.2.tier": "Premium 스타트업 ($79/월)",
    "limit.limits.2.value": "하루 30번",
    "limit.limits.3.tier": "Premium 엔터프라이즈 ($129/월)",
    "limit.limits.3.value": "무제한",
    # ==================== SEARCH ====================
    "search.buildWith": "이것으로 구축할 수 있는 것",
    "search.whoisTitle": "WHOIS 세부 정보",
    "search.whoisLabels.0": "등록 기관",
    "search.whoisLabels.1": "만료일",
    "search.whoisLabels.2": "등록자",
    "search.whoisLabels.3": "네임서버",
    # ==================== SCAN PAGE ====================
    "scanPage.wordList": "단어 목록",
    "scanPage.customWords": "사용자 정의 단어",
    "scanPage.customPlaceholder": "한 줄에 하나씩 단어 입력...",
    "scanPage.tlds": "TLD",
    "scanPage.status": "상태",
    "scanPage.progressLabel": "진행",
    "scanPage.available": "사용 가능",
    "scanPage.results": "결과 ({count}개 도메인)",
    "scanPage.availableOnly": "사용 가능한 것만",
    "scanPage.sortByDomain": "도메인별 정렬",
    "scanPage.sortByPrice": "가격별 정렬",
    "scanPage.exportCsv": "CSV 내보내기",
    "scanPage.domain": "도메인",
    "scanPage.statusHeader": "상태",
    "scanPage.price": "가격",
    "scanPage.actions": "작업",
    "scanPage.availableBadge": "사용 가능",
    "scanPage.errorBadge": "오류",
    "scanPage.takenBadge": "등록됨",
    "scanPage.appraise": "평가",
    # ==================== APPRAISE PAGE ====================
    "appraisePage.desc": "RDAP 데이터, TLD 스코어링, 브랜더빌리티, 상업적 의도 및 나머지 12개 차원에 걸친 포괄적인 밸류에이션.",
    "appraisePage.appraisalsLeft": "오늘 {count}번의 평가 남음",
    "appraisePage.devBypass": "개발 바이패스",
    "appraisePage.activate": "활성화",
    "appraisePage.unlockPrompt": "Premium 플랜으로 나머지 13개 차원을 잠금 해제하세요",
    "appraisePage.whoisHint": "WHOIS + DNS 데이터가 필요하신가요?",
    "appraisePage.domainLookup": "도메인 조회 시도 — 계정 불필요",
    "appraisePage.domainLookupCta": "도메인 조회",
    "appraisePage.deeperHint": "더 깊은 분석이 필요하신가요?",
    "appraisePage.extendedInsights": "확장 인사이트 — 백링크, 상표, 비교 데이터",
    "appraisePage.limitDesc": "오늘 {limit}번의 평가를 모두 사용했습니다. 하루에 {signed}번을 받으려면 계정을 만드세요.",
    # ==================== PREMIUM MODAL ====================
    "premiumModal.title": "Premium 기능",
    "premiumModal.description": "{toolName}에는 Premium 계정이 필요합니다. 이 기능과 더 많은 것을 잠금 해제하려면 가입하세요.",
    "premiumModal.redirecting": "가입 페이지로 리디렉션 중, {count}초 후...",
    "premiumModal.cta": "무료 계정 만들기",
    "premiumModal.back": "돌아가기",
    # ==================== APP HEADER ====================
    "appHeader.home": "홈",
    "appHeader.appraise": "평가",
    "appHeader.scanner": "스캐너",
    "appHeader.marketplace": "마켓플레이스",
    "appHeader.apiKeys": "API 키",
    "appHeader.logout": "로그아웃",
    # ==================== TOOL TEMPLATE ====================
    "toolTemplate.comingSoon": "곧 출시",
    "toolTemplate.waitlistDesc": "이 기능은 적극적으로 개발 중입니다. 우선 접근을 위해 대기 목록에 가입하세요.",
    "toolTemplate.emailPlaceholder": "이메일을 입력하세요",
    "toolTemplate.joinWaitlist": "대기 목록에 가입",
    # ==================== SCAN PAGE (additional) ====================
    "scanPage.noResultsDesc": "스캔 설정을 구성하고 \"스캔 시작\"을 클릭하여 사용 가능한 도메인을 찾으세요.",
    # ==================== APPRAISE PAGE (additional) ====================
    "appraisePage.modules.0": "등록 데이터 (RDAP)",
    "appraisePage.modules.1": "TLD 프리미엄 등급",
    "appraisePage.modules.2": "도메인 길이",
    "appraisePage.modules.3": "단어 수",
    "appraisePage.modules.4": "발음 가능성",
    "appraisePage.modules.5": "단어 분할",
    "appraisePage.modules.6": "키워드 인기",
    "appraisePage.modules.7": "상업적 의도 (CPC)",
    "appraisePage.modules.8": "검색 결과",
    "appraisePage.modules.9": "크로스 TLD 등록",
    "appraisePage.modules.10": "상표 확인",
    "appraisePage.modules.11": "도메인 권위",
    "appraisePage.modules.12": "브랜더빌리티 점수",
    # ==================== SOL AVAILABLE (additional) ====================
    "sol.available.statLabel": "동시 스캔 TLD",
    "sol.available.title": "초고속 사용 가능한 도메인 검색",
    "sol.available.discovery.title": "스마트 도메인 발견",
    "sol.available.timeline.title": "도메인을 놓치지 마세요",
    "sol.available.plansTitle": "플랜 선택",
    "sol.available.popular": "인기",
    "sol.available.getStarted": "시작하기",
    "sol.available.bulk.badge": "엔터프라이즈 기능",
    "sol.available.ctaTitle": "완벽한 도메인 찾기",
    "sol.available.ctaSignup": "무료 계정 만들기",
    "sol.available.ctaScan": "SEO 스캐너 시도",
    # ==================== SOL RESEARCH (additional) ====================
    "sol.research.title": "인수 전 심층 도메인 분석",
    "sol.research.compareTitle": "Ceche 비교",
    "sol.research.ctaTitle": "더 스마트하게 리서치",
    "sol.research.ctaSignup": "무료 계정 만들기",
    "sol.research.ctaAppraise": "평가 도구 시도",
    # ==================== SOL PREMIUM (additional) ====================
    "sol.premium.heroTitle": "자신감 있게 프리미엄 도메인 인수",
    "sol.premium.pricingTitle": "투명한 가격",
    "sol.premium.pricingDesc": "숨겨진 비용 없음. 표시된 가격이 지불하는 가격입니다.",
    "sol.premium.ctaTitle": "지금 프리미엄 도메인 구매",
    "sol.premium.ctaMarketplace": "마켓플레이스 둘러보기",
    "sol.premium.ctaPricing": "가격 보기",
    # ==================== HELP DOCS (additional) ====================
    "helpDocs.title1": "모든 도구,",
    "helpDocs.title2": "문서화됨.",
    "helpDocs.tiersTitle": "구독 등급",
    "helpDocs.needHelp.badge": "도움이 필요하신가요?",
    "helpDocs.needHelp.title": "Premium 구독자는 4시간 지원을 받습니다",
    "helpDocs.needHelp.cta": "지원 문의",
    "helpDocs.openTool": "도구 열기",
    # ==================== HELP FAQ (additional) ====================
    "helpFaq.title1": "자주",
    "helpFaq.title2": "묻는 질문.",
    "helpFaq.stillQuestions": "아직 질문이 있으신가요?",
    "helpFaq.supportTeam": "지원팀이 도와드리겠습니다",
    "helpFaq.contactSupport": "지원 문의",
    "helpFaq.sections.0.title": "시작하기",
    "helpFaq.sections.1.title": "가격 및 결제",
    "helpFaq.sections.2.title": "도구",
    "helpFaq.sections.3.title": "API 및 통합",
    "helpFaq.sections.4.title": "계정 및 지원",
    # ==================== HELP API (additional) ====================
    "helpApi.title1": "Ceche와 함께",
    "helpApi.title2": "빌드하기.",
    "helpApi.baseUrl": "기본 URL",
    "helpApi.auth": "인증",
    "helpApi.endpoints": "엔드포인트",
    "helpApi.rateLimits": "속도 제한",
    "helpApi.enterprise.badge": "엔터프라이즈",
    "helpApi.enterprise.title": "매일 10,000회 API 호출",
    "helpApi.enterprise.cta": "API 키 받기",
    "helpApi.openTool": "도구 열기",
    # ==================== HELP CONTACT (additional) ====================
    "helpContact.badge": "문의하기",
    "helpContact.title1": "연락",
    "helpContact.title2": "주세요.",
    "helpContact.form.name": "이름",
    "helpContact.form.namePlaceholder": "귀하의 이름",
    "helpContact.form.email": "이메일",
    "helpContact.form.subject": "제목",
    "helpContact.form.message": "메시지",
    "helpContact.form.send": "메시지 보내기",
    "helpContact.channels.title": "기타 연락 채널",
    "helpContact.responseTimes.title": "응답 시간",
    "helpContact.businessHours.title": "영업 시간",
    # ==================== HELP CHANGELOG (additional) ====================
    "helpChangelog.badge": "변경 로그",
    "helpChangelog.title1": "모든 커밋,",
    "helpChangelog.title2": "기록됨.",
    "helpChangelog.desc": "모든 업데이트는 git 히스토리에서 직접 가져옵니다. 실제 커밋, 실제 날짜, 실제 설명.",
    "helpChangelog.comingSoon.badge": "출시 예정",
    "helpChangelog.comingSoon.title": "경매 추적, 모바일 앱, ML 밸류에이션",
    "helpChangelog.comingSoon.cta": "로드맵 보기",
    # ==================== MP MAIN (additional) ====================
    "mp.main.badge": "마켓플레이스",
    "mp.main.title": "프리미엄 도메인",
    "mp.main.nameHidden": "이름 숨김",
    "mp.main.revealName": "이름 공개",
    "mp.main.cta.curated": "큐레이션 둘러보기",
    "mp.main.cta.luck": "행운 시도",
    "mp.main.modal.title": "계정 만들기",
    "mp.main.modal.signup": "무료 가입",
    "mp.main.modal.later": "나중에 하기",
    # ==================== MP SELL (additional) ====================
    "mp.sell.badge": "마켓플레이스",
    "mp.sell.title": "도메인 판매",
    "mp.sell.steps.0": "제출",
    "mp.sell.steps.1": "가격 설정",
    "mp.sell.steps.2": "게시",
    "mp.sell.fees.title": "요금 구조",
    "mp.sell.fees.listing.title": "등록 수수료",
    "mp.sell.fees.commission.title": "수수료 요율",
    "mp.sell.eligibility.title": "자격 요건 체크리스트",
    "mp.sell.tools.title": "판매자 도구",
    "mp.sell.cta.title": "판매할 준비가 되셨나요?",
    "mp.sell.cta.signup": "계정 만들기",
    "mp.sell.cta.pricing": "가격 보기",
    # ==================== MP LUCK (additional) ====================
    "mp.luck.badge": "마켓플레이스",
    "mp.luck.title": "행운 시도",
    "mp.luck.step1": "1단계: TLD 선택",
    "mp.luck.spinning": "회전 중...",
    "mp.luck.step2": "2단계: 상자 선택",
    "mp.luck.clickToReveal": "클릭하여 공개",
    "mp.luck.howItWorks.title": "작동 방식",
    "mp.luck.cta.marketplace": "마켓플레이스 보기",
    "mp.luck.cta.signup": "무료 가입",
    "mp.luck.modal.title": "계정 만들기",
    "mp.luck.modal.signup": "무료 가입",
    "mp.luck.modal.later": "나중에 하기",
    # ==================== MP CURATED (additional) ====================
    "mp.curated.badge": "마켓플레이스",
    "mp.curated.title": "큐레이션 도메인",
    "mp.curated.tryLuck": "행운 시도",
    "mp.curated.howItWorks.title": "작동 방식",
    "mp.curated.cta.marketplace": "마켓플레이스 보기",
    "mp.curated.cta.luck": "행운 시도",
    # ==================== MP UNMASKING (additional) ====================
    "mp.unmasking.badge": "마켓플레이스",
    "mp.unmasking.title": "공개 메커니즘 작동 방식",
    "mp.unmasking.howItWorks.title": "작동 방식",
    "mp.unmasking.vault.title": "볼트 보호",
    "mp.unmasking.cta.marketplace": "마켓플레이스 둘러보기",
    "mp.unmasking.cta.luck": "행운 시도",
    # ==================== SOL INDEX (additional) ====================
    "sol.index.title": "모든 도메인 필요를 위한 솔루션",
    "sol.index.cta.ready": "준비되셨나요?",
    "sol.index.cta.signup": "무료 계정 만들기",
    "sol.index.learnMore": "자세히 보기 →",
    # ==================== SOL INVESTORS (additional) ====================
    "sol.investors.badge": "투자자를 위한",
    "sol.investors.title": "도메인 투자 수익 극대화",
    "sol.investors.toolsTitle": "투자자를 위한 도구",
    "sol.investors.gettingStarted.title": "시작하기",
    "sol.investors.ctaTitle": "더 스마트하게 플리핑 시작",
    "sol.investors.ctaSignup": "무료 계정 만들기",
    "sol.investors.ctaMarketplace": "마켓플레이스 둘러보기",
    # ==================== SOL FOUNDERS (additional) ====================
    "sol.founders.badge": "창업자를 위한",
    "sol.founders.title": "올바른 도메인으로 브랜드 구축",
    "sol.founders.builtForTitle": "창업자를 위해 구축",
    "sol.founders.ctaTitle": "브랜드 도메인 찾기",
    "sol.founders.ctaSignup": "무료 계정 만들기",
    "sol.founders.ctaAppraise": "평가 도구 시도",
    # ==================== SOL AGENCIES (additional) ====================
    "sol.agencies.badge": "대행사를 위한",
    "sol.agencies.title": "고객을 위한 도메인 인수 확장",
    "sol.agencies.whyTitle": "대행사가 Ceche를 선택하는 이유",
    "sol.agencies.plansTitle": "모든 대행사를 위한 플랜",
    "sol.agencies.plansDesc": "독립 컨설턴트부터 풀서비스 대행사까지 확장",
    "sol.agencies.ctaTitle": "대행사를 확장할 준비가 되셨나요?",
    "sol.agencies.ctaSignup": "무료 계정 만들기",
    "sol.agencies.ctaApi": "API 문서",
    # ==================== RES INDEX (additional) ====================
    "res.index.title": "리소스",
    "res.index.subtitle": "학습 및 지원 받기",
    # ==================== RES BLOG (additional) ====================
    "res.blog.badge": "Ceche 블로그",
    "res.blog.title": "도메인 인텔리전스 디코딩.",
    "res.blog.topicsBadge": "주제",
    "res.blog.cta.ebooks": "전자책 둘러보기 →",
    "res.blog.cta.pricing": "가격 보기",
    # ==================== RES EBOOKS (additional) ====================
    "res.ebooks.badge": "Ceche 전자책",
    "res.ebooks.title": "도메인 투자 심층 분석",
    "res.ebooks.getCopy": "무료 사본 받기",
    "res.ebooks.cta.blog": "블로그 읽기",
    "res.ebooks.cta.pricing": "가격 보기",
    # ==================== RES CASES (additional) ====================
    "res.cases.badge": "사례 연구",
    "res.cases.title": "실제 투자자. 실제 결과.",
    "res.cases.cta.contact": "문의하기 →",
    # ==================== COMPANY ABOUT (additional) ====================
    "company.about.badge": "Ceche 소개",
    "company.about.title": "데이터 기반 투자를 위해 구축",
    "company.about.cta.0": "평가 시도 →",
    "company.about.cta.1": "마켓플레이스 둘러보기",
    "company.about.origin.badge": "우리의 기원",
    "company.about.origin.title": "시장에 더 나은 데이터가 필요하다는 것을 발견한 도메인 투자자가 설립",
    "company.about.founder.label": "창립자",
    "company.about.values.badge": "우리의 신념",
    "company.about.values.title": "모든 결정을 이끄는 세 가지 원칙",
    "company.about.values.items.0.title": "투명성",
    "company.about.values.items.1.title": "데이터 엄격성",
    "company.about.values.items.2.title": "속도",
    # ==================== COMPANY AFFILIATES (additional) ====================
    "company.affiliates.badge": "Ceche 파트너",
    "company.affiliates.title": "도메인 투자자를 추천하여 수익 창출",
    "company.affiliates.timeline.0": "가입",
    "company.affiliates.timeline.1": "링크 공유",
    "company.affiliates.timeline.2": "30% 수익",
    "company.affiliates.cta.title": "지금 수익 창출 시작",
    "company.affiliates.cta.join": "파트너 프로그램 참여 →",
    "company.affiliates.cta.pricing": "가격 보기",
    "company.affiliates.cta.support": "지원 문의",
}

def set_nested(d, path, value):
    keys = path.split('.')
    for key in keys[:-1]:
        if key.isdigit():
            d = d[int(key)]
        else:
            d = d[key]
    last = keys[-1]
    if last.isdigit():
        d[int(last)] = value
    else:
        d[last] = value

applied = 0
skipped = 0
for path, value in korean_translations.items():
    try:
        set_nested(ko, path, value)
        applied += 1
    except (KeyError, IndexError, TypeError) as e:
        print(f"SKIP {path}: {e}")
        skipped += 1

with open('messages/ko.json', 'w', encoding='utf-8') as f:
    json.dump(ko, f, ensure_ascii=False, indent=2)

# Count Korean strings
def count_korean(obj):
    count = 0
    if isinstance(obj, dict):
        for v in obj.values():
            count += count_korean(v)
    elif isinstance(obj, list):
        for v in obj:
            count += count_korean(v)
    elif isinstance(obj, str) and obj and len(obj) > 3:
        has_korean = any('\uac00' <= c <= '\ud7af' for c in obj)
        if has_korean:
            count += 1
    return count

korean_count = count_korean(ko)
print(f"Done! {applied} translations applied, {skipped} skipped, {korean_count} Korean strings in ko.json.")
