package appraisal

// Word lists for segmentation and grading
// These are extracted from the graded_wordlist.json and Go embedded lists

func float64Ptr(v float64) *float64 { return &v }

func isCommonWord(word string) bool {
	_, ok := commonWords[word]
	return ok
}

// isKnownWord checks if a word is in any of our dictionaries.
func isKnownWord(word string) bool {
	if isCommonWord(word) {
		return true
	}
	if _, ok := builtinWords[word]; ok {
		return true
	}
	if _, ok := techWords[word]; ok {
		return true
	}
	if _, ok := businessWords[word]; ok {
		return true
	}
	if _, ok := creativeWords[word]; ok {
		return true
	}
	return false
}

var builtinWords = map[string]bool{
	"go": true, "app": true, "web": true, "data": true, "net": true,
	"cloud": true, "tech": true, "dev": true, "hub": true, "lab": true,
	"box": true, "top": true, "pro": true, "max": true, "one": true,
	"ai": true, "api": true, "bit": true, "pay": true, "buy": true,
	"sell": true, "shop": true, "store": true, "market": true, "trade": true,
	"crypto": true, "block": true, "chain": true, "meta": true, "open": true,
	"fast": true, "quick": true, "easy": true, "smart": true, "blue": true,
	"prime": true, "ultra": true, "mega": true, "super": true,
	"pulse": true, "spark": true, "flow": true, "sync": true,
	"core": true, "base": true, "flex": true, "zoom": true, "wave": true,
	"access": true, "account": true, "agent": true, "analytics": true,
	"archive": true, "audio": true, "auto": true, "backend": true,
	"bank": true, "bill": true, "book": true, "build": true,
	"business": true, "calendar": true, "camp": true, "capital": true,
	"card": true, "care": true, "career": true, "cash": true,
	"chat": true, "check": true, "city": true, "class": true,
	"clean": true, "click": true, "client": true, "club": true,
	"code": true, "college": true, "commerce": true, "company": true,
	"connect": true, "consulting": true, "contact": true, "control": true,
	"cook": true, "copy": true, "creative": true, "cube": true,
	"currency": true, "customer": true, "dance": true, "deal": true,
	"design": true, "digital": true, "direct": true, "docs": true,
	"domain": true, "drive": true, "drop": true, "earn": true,
	"education": true, "electric": true, "email": true, "engage": true,
	"engine": true, "enterprise": true, "event": true, "exchange": true,
	"express": true, "farm": true, "finance": true, "fit": true,
	"fitness": true, "food": true, "foot": true, "frame": true,
	"fresh": true, "fund": true, "fusion": true, "game": true,
	"gear": true, "gift": true, "global": true, "golf": true,
	"good": true, "green": true, "group": true, "growth": true,
	"guard": true, "guide": true, "guru": true, "gym": true,
	"health": true, "heart": true, "home": true, "hook": true,
	"host": true, "house": true, "hunt": true, "ice": true,
	"idea": true, "image": true, "inbox": true, "india": true,
	"ink": true, "input": true, "insight": true, "instinct": true,
	"institute": true, "insurance": true, "intern": true, "invest": true,
	"io": true, "island": true, "jet": true, "job": true,
	"join": true, "journal": true, "joy": true, "jump": true,
	"justice": true, "keep": true, "key": true, "kid": true,
	"kitchen": true, "land": true, "law": true,
	"lawyer": true, "lead": true, "learn": true, "legal": true,
	"life": true, "light": true, "link": true, "list": true,
	"live": true, "loan": true, "local": true, "lock": true,
	"logo": true, "love": true, "mail": true, "main": true,
	"manage": true, "map": true, "margin": true, "mark": true,
	"media": true, "meet": true, "menu": true,
	"merge": true, "metal": true, "mind": true, "mix": true,
	"mobile": true, "mode": true, "money": true, "moon": true,
	"mortgage": true, "motor": true, "music": true,
	"network": true, "news": true, "next": true, "node": true,
	"note": true, "office": true, "online": true,
	"option": true, "oracle": true, "order": true, "organ": true,
	"page": true, "paint": true, "pan": true, "park": true,
	"partner": true, "path": true, "peer": true,
	"phone": true, "photo": true, "piano": true, "pic": true,
	"plan": true, "play": true, "pod": true, "point": true,
	"pool": true, "pop": true, "power": true, "press": true,
	"price": true, "print": true, "privacy": true, "private": true,
	"profit": true, "project": true, "promo": true, "property": true,
	"public": true, "publish": true, "quest": true, "quote": true,
	"radio": true, "range": true, "rate": true, "read": true,
	"real": true, "record": true, "recruit": true, "rent": true,
	"report": true, "research": true, "resource": true, "rest": true,
	"retail": true, "review": true, "ride": true, "risk": true,
	"robot": true, "rock": true, "role": true, "room": true,
	"root": true, "route": true, "run": true, "safe": true,
	"sale": true, "salt": true, "sand": true, "save": true,
	"scan": true, "school": true, "score": true, "search": true,
	"secure": true, "select": true, "serve": true, "service": true,
	"session": true, "set": true, "share": true, "ship": true,
	"show": true, "side": true, "site": true,
	"snap": true, "social": true, "solar": true,
	"solution": true, "sonic": true, "source": true, "space": true,
	"sport": true, "spot": true, "stage": true, "start": true,
	"state": true, "stock": true, "stream": true,
	"studio": true, "style": true, "supply": true, "support": true,
	"system": true, "tab": true, "talk": true,
	"target": true, "task": true, "tax": true, "team": true,
	"term": true, "test": true, "text": true,
	"time": true, "tip": true, "today": true, "tool": true,
	"tour": true, "town": true, "track": true,
	"train": true, "trend": true, "trip": true,
	"truck": true, "trust": true, "tube": true, "tune": true,
	"tv": true, "university": true, "up": true, "us": true,
	"value": true, "video": true, "view": true, "village": true,
	"vinyl": true, "visa": true, "vision": true, "voice": true,
	"volume": true, "vote": true, "wage": true, "watch": true,
	"water": true, "week": true,
	"weight": true, "wheel": true, "win": true, "wire": true,
	"wise": true, "work": true, "world": true, "zone": true,
}

var techWords = map[string]bool{
	"app": true, "api": true, "code": true, "dev": true, "cloud": true,
	"data": true, "ai": true, "ml": true, "iot": true,
	"block": true, "chain": true, "crypto": true, "web": true, "mobile": true,
	"stack": true, "byte": true, "bit": true, "node": true, "react": true,
	"vue": true, "angular": true, "swift": true, "kotlin": true, "rust": true,
	"python": true, "java": true, "script": true, "type": true, "sql": true,
	"git": true, "hub": true, "lab": true, "tech": true, "digital": true,
	"smart": true, "auto": true, "robot": true, "drone": true, "vr": true,
	"ar": true, "quantum": true, "neural": true, "deep": true, "learn": true,
	"model": true, "mining": true, "analytics": true, "insight": true,
	"metrics": true, "dashboard": true, "report": true, "track": true,
	"monitor": true, "alert": true, "notify": true, "sync": true, "backup": true,
	"secure": true, "vault": true, "shield": true, "fire": true, "wall": true,
	"proxy": true, "vpn": true, "ssl": true, "tls": true,
}

var businessWords = map[string]bool{
	"pay": true, "buy": true, "sell": true, "trade": true, "market": true,
	"store": true, "shop": true, "cart": true, "checkout": true, "invoice": true,
	"bill": true, "tax": true, "fund": true, "invest": true, "bank": true,
	"loan": true, "credit": true, "debit": true, "wallet": true, "cash": true,
	"coin": true, "token": true, "stock": true, "bond": true, "equity": true,
	"asset": true, "portfolio": true, "wealth": true, "capital": true,
	"venture": true, "angel": true, "seed": true, "series": true, "round": true,
	"valuation": true, "exit": true, "ipo": true, "merger": true, "acquisition": true,
	"deal": true, "partner": true, "affiliate": true, "commission": true,
	"revenue": true, "profit": true, "margin": true, "cost": true, "price": true,
	"discount": true, "coupon": true, "promo": true, "loyalty": true,
	"reward": true, "points": true,
}

var creativeWords = map[string]bool{
	"design": true, "art": true, "creative": true, "studio": true, "gallery": true,
	"canvas": true, "color": true, "palette": true, "font": true, "type": true,
	"logo": true, "brand": true, "identity": true, "style": true, "fashion": true,
	"trend": true, "vogue": true, "chic": true, "sleek": true, "modern": true,
	"retro": true, "vintage": true, "classic": true, "elegant": true, "luxury": true,
	"premium": true, "elite": true, "craft": true, "handmade": true, "artisan": true,
	"custom": true, "bespoke": true, "unique": true, "rare": true, "exclusive": true,
	"limited": true, "special": true, "vip": true, "magic": true, "wonder": true,
	"dream": true, "fantasy": true, "story": true, "narrative": true,
	"voice": true, "sound": true, "music": true, "rhythm": true, "beat": true,
	"pulse": true, "vibe": true,
}

var commonWords = map[string]bool{
	"go": true, "app": true, "web": true, "data": true, "net": true,
	"cloud": true, "tech": true, "dev": true, "hub": true, "lab": true,
	"box": true, "top": true, "pro": true, "max": true, "one": true,
	"ai": true, "api": true, "bit": true, "pay": true, "buy": true, "my": true,
	"sell": true, "shop": true, "store": true, "market": true, "trade": true,
	"crypto": true, "block": true, "chain": true, "meta": true, "open": true,
	"fast": true, "quick": true, "easy": true, "smart": true, "blue": true,
	"prime": true, "ultra": true, "mega": true, "super": true,
	"pulse": true, "spark": true, "flow": true, "sync": true,
	"core": true, "base": true, "flex": true, "zoom": true, "wave": true,
	"access": true, "account": true, "agent": true, "analytics": true,
	"archive": true, "audio": true, "auto": true, "backend": true,
	"bank": true, "bill": true, "book": true, "build": true,
	"business": true, "calendar": true, "camp": true, "capital": true,
	"card": true, "care": true, "career": true, "cash": true,
	"chat": true, "check": true, "city": true, "class": true,
	"clean": true, "click": true, "client": true, "club": true,
	"code": true, "college": true, "commerce": true, "company": true,
	"connect": true, "consulting": true, "contact": true, "control": true,
	"cook": true, "copy": true, "creative": true, "cube": true,
	"currency": true, "customer": true, "dance": true, "deal": true,
	"design": true, "digital": true, "direct": true, "docs": true,
	"domain": true, "drive": true, "drop": true, "earn": true,
	"education": true, "electric": true, "email": true, "engage": true,
	"engine": true, "enterprise": true, "event": true, "exchange": true,
	"express": true, "farm": true, "finance": true, "fit": true,
	"fitness": true, "food": true, "foot": true, "frame": true,
	"fresh": true, "fund": true, "fusion": true, "game": true,
	"gear": true, "gift": true, "global": true, "golf": true,
	"good": true, "green": true, "group": true, "growth": true,
	"guard": true, "guide": true, "guru": true, "gym": true,
	"health": true, "heart": true, "home": true, "hook": true,
	"host": true, "house": true, "hunt": true, "ice": true,
	"idea": true, "image": true, "inbox": true, "india": true,
	"ink": true, "input": true, "insight": true, "instinct": true,
	"institute": true, "insurance": true, "intern": true, "invest": true,
	"io": true, "island": true, "jet": true, "job": true,
	"join": true, "journal": true, "joy": true, "jump": true,
	"justice": true, "keep": true, "key": true, "kid": true,
	"kitchen": true, "land": true, "law": true,
	"lawyer": true, "lead": true, "learn": true, "legal": true,
	"life": true, "light": true, "link": true, "list": true,
	"live": true, "loan": true, "local": true, "lock": true,
	"logo": true, "love": true, "mail": true, "main": true,
	"manage": true, "map": true, "margin": true, "mark": true,
	"media": true, "meet": true, "menu": true,
	"merge": true, "metal": true, "mind": true, "mix": true,
	"mobile": true, "mode": true, "money": true, "moon": true,
	"mortgage": true, "motor": true, "music": true,
	"network": true, "news": true, "next": true, "node": true,
	"note": true, "office": true, "online": true,
	"option": true, "oracle": true, "order": true, "organ": true,
	"page": true, "paint": true, "pan": true, "park": true,
	"partner": true, "path": true, "peer": true,
	"phone": true, "photo": true, "piano": true, "pic": true,
	"plan": true, "play": true, "pod": true, "point": true,
	"pool": true, "pop": true, "power": true, "press": true,
	"price": true, "print": true, "privacy": true, "private": true,
	"profit": true, "project": true, "promo": true, "property": true,
	"public": true, "publish": true, "quest": true, "quote": true,
	"radio": true, "range": true, "rate": true, "read": true,
	"real": true, "record": true, "recruit": true, "rent": true,
	"report": true, "research": true, "resource": true, "rest": true,
	"retail": true, "review": true, "ride": true, "risk": true,
	"robot": true, "rock": true, "role": true, "room": true,
	"root": true, "route": true, "run": true, "safe": true,
	"sale": true, "salt": true, "sand": true, "save": true,
	"scan": true, "school": true, "score": true, "search": true,
	"secure": true, "select": true, "serve": true, "service": true,
	"session": true, "set": true, "share": true, "ship": true,
	"show": true, "side": true, "site": true,
	"snap": true, "social": true, "solar": true,
	"solution": true, "sonic": true, "source": true, "space": true,
	"sport": true, "spot": true, "stage": true, "start": true,
	"state": true, "stock": true, "stream": true,
	"studio": true, "style": true, "supply": true, "support": true,
	"system": true, "tab": true, "talk": true,
	"target": true, "task": true, "tax": true, "team": true,
	"term": true, "test": true, "text": true,
	"time": true, "tip": true, "today": true, "tool": true,
	"tour": true, "town": true, "track": true,
	"train": true, "trend": true, "trip": true,
	"truck": true, "trust": true, "tube": true, "tune": true,
	"tv": true, "university": true, "up": true, "us": true,
	"value": true, "video": true, "view": true, "village": true,
	"vinyl": true, "visa": true, "vision": true, "voice": true,
	"volume": true, "vote": true, "wage": true, "watch": true,
	"water": true, "week": true,
	"weight": true, "wheel": true, "win": true, "wire": true,
	"wise": true, "work": true, "world": true, "zone": true,
}

// Graded intent word lists (high commercial intent)
var highIntentWords = []string{
	"insurance", "insurances", "lawyer", "lawyers", "attorney", "attorneys",
	"mortgage", "mortgages", "credit", "loans", "loan",
	"hosting", "host", "website", "software", "casino", "poker",
	"betting", "trading", "trader", "crypto", "bitcoin", "ethereum",
	"seo", "vpn", "plumber", "electrician", "dentist", "dental",
	"clinic", "surgery", "hospital", "healthcare", "pharmacy",
	"dating", "cbd", "roofing", "pest", "storage", "locksmith",
	"bail", "bond", "wrongful", "tax", "accounting",
	"saas", "consulting", "marketing", "agency", "real", "estate",
	"cloud", "devops", "fintech", "cyber",
}

var midIntentWords = []string{
	"travel", "hotel", "car", "design", "fashion", "beauty",
	"wedding", "fitness", "education", "course", "training",
	"coach", "tutor", "catering", "event", "photography",
	"photographer", "bakery", "rental", "charter", "cruise",
	"resort", "wellness", "skincare", "jewelry", "watch",
	"boutique", "outlet", "wholesale", "retail", "ecommerce",
	"shopify", "woocommerce", "marketplace",
}

var lowIntentWords = []string{
	"blog", "news", "forum", "chat", "free", "download",
	"wiki", "dictionary", "calculator", "converter", "tool",
	"template", "checker", "tester", "scanner", "generator",
	"builder", "maker", "creator", "finder", "tracker",
	"monitor", "logger", "analyzer", "simulator", "emulator",
	"game", "play", "player", "video", "music", "audio",
	"image", "photo", "picture", "movie", "film", "book",
	"podcast", "radio", "stream", "streaming", "live",
	"info", "information", "guide", "tutorial",
	"howto", "review", "best", "top", "list", "collection",
	"directory", "index", "archive", "library",
}
